/* words/_evo_data.js — ⏳ 單字時光機：每一個字一頁、一頁三幕（使用者 2026-09-28 指定，第 6(4)E 點）
 *
 *   (a) 為什麼拼法變了？      ➜ 時光隧道：一站一站演給學生看，每一站都寫「大約 N 年前」
 *   (b) 以前／現在大對比       ➜ 字母一格一格對齊：一樣的綠色、換掉的金色、不見的紅色、多出來的藍色
 *   (c) 以前會唸、現在不唸的字母 ➜ 那幾個字母先亮、再慢慢變灰；沒有這種字母的字不硬湊，
 *                              照實講那個字真正有趣的地方（fun）
 *
 * 事實判準（AGENTS.md 最高原則）：只寫查得到的。每一幕的出處都寫在那一幕（src），**不寫通則**。
 * 年代換算：今天 ＝ 2026 年。古英文（Old English）＝ 大約 450～1150 年，留下來的書多半寫在
 * 1000 年前左右，所以一律寫「大約 1000 年前」；中古英文寫出確切的世紀（c.1200 ＝ 大約 800 年前、
 * c.1300 ＝ 大約 700 年前、c.1400 ＝ 大約 600 年前）；gh 的聲音、字尾 e 在大約 1600 年（莎士比亞的時代）
 * 已經不唸 ＝ 大約 400 年前。
 *
 * 欄位：
 *   w     檔名（跟字卡一樣）   show 畫面上的字   zh 中文
 *   st    時光隧道每一站：[拼法, 大約幾年前, 那時候叫什麼語言]（最後一站 ＝ 今天）
 *   al    (b) 字母對齊：用空白隔開，「舊=新」一樣、「舊>新」換掉、「舊>」不見、「>新」多出來
 *   a     (a) {q 題目, o[正解,錯,錯,錯], l[一句, 一句]}
 *   c     (c) {m 單字，[ ] 括起來的是不唸的字母, q, o, was 以前怎麼唸, lost 什麼時候不唸, cmp [語言, 字, 國旗, 中文]}
 *   fun   (c) 沒有「以前會唸、現在不唸」的字母：{t 標題, q, o, h 動畫, l[一句, 一句]}
 *   src   {a:[出處], b:[出處], c:[出處]}：每一條 [t 主題, s 證據在哪一本, d 翻開會看到]
 */

/* ── 很多字共用的證據（但每一幕只放跟那個字有關的那一條）── */
const S = {
 oe:  ['古英文 ＝ 大約 1000 年前', 'Wikipedia「Old English」', '古英文是大約 450～1150 年的英文；留下來的書，大多寫在<b>一千年前左右</b>。'],
 gh:  ['gh 以前會唸', 'Wikipedia「Gh (digraph)」「Yogh」', 'gh 是法國來的抄書人寫「喉嚨呼氣的 h 音」（像德文 ach）的方法；標準英文<b>大約 1600 年以前</b>都還唸，後來才不唸。'],
 fe:  ['字尾 e 以前會唸', 'Harvard 大學 Geoffrey Chaucer 網站「The Loss of Final -e」', '喬叟的時代（大約 1390 年）字尾 e 大多唸成輕輕的「ㄜ」；<b>到莎士比亞的時代（大約 1600 年）已經不唸了</b>。'],
 gvs: ['母音大搬家', 'Wikipedia「Great Vowel Shift」', '大約 <b>1400～1700 年</b>，英文的長母音全部換了聲音：<b>ī（ㄧ）➜ 今天的 i（ㄞ）</b>、<b>ā（ㄚ）➜ 今天的 a（ㄝ）</b>、<b>ū（ㄨ）➜ ow（ㄠ）</b>。拼法沒有跟著改。'],
 hw:  ['hw 變成 wh', 'Wikipedia「Pronunciation of English ⟨wh⟩」；Language Log「Hwæt about WH?」', '古英文寫 <b>hw</b>（hwæt、hwā、hwǣr、hwanne、hwȳ）；<b>大約 850 年前</b>（1100 年代的《Ormulum》）開始寫成 wh，學 ch、th、sh 那樣把 h 放後面。'],
 thorn:['þ 變成 th', 'Wikipedia「Thorn (letter)」', 'th 從 1300 年代開始流行；<b>1476 年</b>英國第一台印刷機的鉛字是從荷蘭、比利時買來的，<b>沒有 þ</b>，þ 就慢慢消失了。'],
 so:  ['u 為什麼寫成 o', 'Wikipedia「O」；The Literacy Nest「Scribal O」', '以前手寫的 u、n、m、v 都是一根一根的直線，連在一起<b>根本分不出來</b>；抄書的人就把 u 改寫成 <b>o</b>（son、love、come、month），<b>聲音沒變</b>。'],
 uv:  ['u 和 v 以前是同一個字母', 'Etymonline「V」；Wikipedia「V」', '中古英文 u、v 混著用；<b>大約 1630 年</b>才分成「v ＝ 子音、u ＝ 母音」。'],
 fv:  ['古英文 f 在兩個母音中間唸 v', 'Wikipedia「V」；Old English Online「Advanced Pronunciation Guide」', '古英文 <b>seofon</b>（七）、heofon（天）的 f 夾在母音中間，<b>唸 v</b>；後來才改寫成 v。'],
 fr:  ['1066 年以後的法文字', 'Merriam-Webster「Norman Conquest: New English Words」；Britannica', '1066 年法國諾曼第公爵當上英國國王，<b>幾千個法文字</b>進了英文：法律、政府、食物……家人的 uncle、aunt、cousin 也是。'],
 ap:  ['’ 是印刷工人帶來的', 'Oxford University Press Blog「How apostrophes came to confuse us」(2017)；English Language & Linguistics (Cambridge, 2023)「the apostrophe in the history of English」', '’ 大約在 <b>1550 年左右（大約 470 年前）</b>進入英文的印刷品，用來表示「<b>這裡少了字母</b>」。'],
 v:   ['英文字不用 v 結尾', 'Wikipedia「English orthography」', '英文習慣不讓 <b>v</b> 站在字尾，所以寫成 <b>-ve</b>：give、have、love、five、twelve。']
};
const E = (t, s, d) => ({ t, s, d });
const C = k => E.apply(null, S[k]);
const ety = (w, d) => E(w + ' 的來源', 'Etymonline（Online Etymology Dictionary）「' + w + '」', d);

const EVO = [
/* ═════════════ 🔢 三年級：數字 ═════════════ */
{w:'zero', zh:'零',
 st:[['śūnya','1400','印度梵文'],['ṣifr','1200','阿拉伯文'],['zephirum','800','拉丁文'],['zero','400','義大利文 ➜ 英文'],['zero','今天','英文']],
 al:'z=z e=e phi> r=r um>o',
 a:{q:'「零」這個字，怎麼一路走到英文？', o:['印度 ➜ 阿拉伯 ➜ 義大利 ➜ 英國','英國自己發明的','美國 ➜ 英國','日本 ➜ 英國'],
    l:['「<b>空的</b>」這個字，從印度一路傳到英國','義大利人把 <b>zephirum</b> 唸短，變成 <b>zero</b>']},
 fun:{t:'zero 的雙胞胎兄弟', q:'哪一個英文字，跟 zero 是<b>同一個阿拉伯字</b>變來的？', o:['cipher 密碼','zebra 斑馬','hero 英雄','zoo 動物園'],
    h:'<div class="evsp"><span class="c1">ṣifr<em>阿拉伯文：空的</em></span><span class="ar">⬋ ⬊</span><span class="two"><b>zero</b><em>零</em></span><span class="two"><b>cipher</b><em>密碼</em></span></div>',
    l:['同一個字 <b>ṣifr</b>，分成兩兄弟：<b>zero</b> 和 <b>cipher</b>']},
 src:{a:[E('0 的旅行','Wikipedia「0」「Brahmagupta」「Fibonacci」','<b>628 年</b>印度 Brahmagupta 把 0 當數字來算（梵文 śūnya ＝ 空的）➜ 阿拉伯文 <b>ṣifr</b> ➜ <b>1202 年</b> Fibonacci 寫進書裡。'),
         ety('zero','<b>1600 年左右</b>（大約 400 年前）進入英文：義大利文 <b>zero</b> ← 中世紀拉丁文 <b>zephirum</b> ← 阿拉伯文 <b>ṣifr</b>。')],
      b:[ety('zero','義大利文 zefiro 唸快了變成 <b>zero</b>（威尼斯的說法 zevero）。')],
      c:[ety('cipher','<b>cipher</b> 也是阿拉伯文 <b>ṣifr</b> 變的：先是「零」，後來變成「密碼」。')]}},

{w:'one', zh:'一',
 st:[['ān','1000','古英文'],['oon','600','中古英文'],['one','今天','英文']],
 al:'a>o n=n >e',
 a:{q:'一千年前的「一」，拼法跟今天比？', o:['a 變成 o，後面多一個 e','完全一樣','多一個 w','少一個 n'],
    l:['<b>ān</b> 的 a 慢慢唸成 o，就寫成 <b>oon ➜ one</b>','{{alone}}、{{only}} 裡面，還藏著以前的 one']},
 c:{m:'on[e]', q:'one 的哪一個字母<b>不唸</b>？', o:['字尾的 e','o','n','全部都唸'],
    was:'one 唸 /wʌn/：開頭有一個 <b>w 的聲音</b>，卻<b>沒有寫出來</b>！', lost:'大約 600 年前（1400 年代）開始有人這樣唸，大約 1700 年變成標準',
    l:['字尾 <b>e</b> 不唸','反過來：唸出來的 <b>w</b>，拼字裡<b>找不到</b>']},
 src:{a:[C('oe'),ety('one','古英文 <b>ān</b>（a 唸「ㄚ」）；{{alone}} ＝ all ＋ one、{{only}} ＝ one ＋ -ly，還留著以前的唸法。')],
      b:[ety('one','古英文 ān ➜ 中古英文 oon、on ➜ one。')],
      c:[E('one 的 w 從哪裡來','Grammarphobia Blog「Why ‘one’ sounds like ‘won’」(2023)','「won」的唸法 <b>1400 年代</b>從英國部分地區傳開，<b>1600 年代後期</b>才變成標準；印刷術已經把拼法 one 固定下來了。')]}},

{w:'two', zh:'二',
 st:[['twā','1000','古英文'],['two','600','中古英文'],['two','今天','英文']],
 al:'t=t w=w a>o',
 a:{q:'一千年前的 two，拼法跟今天差在哪？', o:['最後的 a 變成 o','多了一個 w','少了一個 t','完全不一樣'],
    l:['<b>twā</b> 的 a 慢慢唸成 o ➜ <b>two</b>','w 以前<b>有唸</b>，拼法就留下來了']},
 c:{m:'t[w]o', q:'two 的哪一個字母<b>不唸</b>？', o:['w','t','o','全部都唸'],
    was:'以前唸「<b>t-w-a</b>」，w 有聲音', lost:'a 變成 o 以後，嘴巴已經嘟起來，<b>w 就被吃掉了</b>（who 也一樣）',
    cmp:['nl-NL','twee','nl','荷蘭文：二'], l:['荷蘭文 <b>twee</b>：w 到今天<b>還在唸</b>','{{twin}}、{{twice}} 的 w 也還在唸']},
 src:{a:[C('oe'),ety('two','古英文 <b>twā</b>，w 有唸出來。')],
      b:[ety('two','古英文 twā ➜ 中古英文 two。')],
      c:[E('two、who 一起掉了 w','Wikipedia「Pronunciation of English ⟨wh⟩」','古英文 <b>twā ➜ two ➜ /tuː/</b>，跟 <b>hwā ➜ who ➜ /huː/</b> 走的是同一條路：母音變成 o、u 以後，w 就不唸了。'),
         E('荷蘭文還在唸','Van Dale「twee」','荷蘭文的「二」<b>twee</b>，w 到今天還唸出來。')]}},

{w:'three', zh:'三',
 st:[['þrēo','1000','古英文'],['thre','700','中古英文'],['three','今天','英文']],
 al:'þ>th r=r ē=e o>e',
 a:{q:'<b>þ</b> 這個字母，後來變成了？', o:['th','p','b','d'],
    l:['古英文用一個像小旗子的字母 <b>þ</b>','印刷機沒有 þ，就改寫成 <b>th</b>']},
 fun:{t:'ee ＝ 拉長音', q:'three 的 <b>ee</b> 唸幾個聲音？', o:['一個長長的 ㄧ','兩個 ㄝ','不唸','ㄞ'],
    h:'<div class="evsp"><span class="two"><b>thr<i class="evr">ee</i></b><em>ee ＝ 一個長長的 /iː/</em></span></div>',
    l:['<b>ee</b> 兩個字母，只唸一個<b>拉長</b>的 ㄧ','{{see}}、{{tree}}、{{green}} 都一樣']},
 src:{a:[C('oe'),ety('three','古英文 <b>þrēo</b>，第一個字母是 <b>þ（thorn）</b>。'),C('thorn')],
      b:[C('thorn')],
      c:[E('ee 唸 /iː/','Cambridge Dictionary「three」（US /θriː/）','three 的 <b>ee</b> 兩個字母只唸<b>一個長母音 /iː/</b>。')]}},

{w:'four', zh:'四',
 st:[['fēower','1000','古英文'],['four','600','中古英文'],['four','今天','英文']],
 al:'f=f ēo>o we> >u r=r',
 a:{q:'一千年前的 four，比今天？', o:['比較長：fēower','比較短：fr','完全一樣','少一個 r：fou'],
    l:['<b>fēower</b> 唸快了，中間的 <b>we</b> 不見了','中古英文寫成 <b>four</b>，一直用到今天']},
 fun:{t:'forty 沒有 u！', q:'「四十」怎麼拼？', o:['forty','fourty','fourtee','forti'],
    h:'<div class="evsp"><span class="two"><b>fo<i class="evr">u</i>r</b><em>四</em></span><span class="two"><b>fo<i class="evr">u</i>rteen</b><em>十四</em></span><span class="two"><b>forty</b><em>四十：<i class="evno">沒有 u</i></em></span></div>',
    l:['four、fourteen 有 <b>u</b>','<b>forty</b> 沒有 u！']},
 src:{a:[C('oe'),ety('four','古英文 <b>fēower</b>；德文 vier、荷蘭文 vier 都是它的家人。')],
      b:[ety('four','古英文 fēower ➜ 中古英文 four。')],
      c:[E('forty 沒有 u','Cambridge Dictionary「forty」「fourteen」','四十拼成 <b>forty</b>，<b>不是 fourty</b>；十四是 fourteen（有 u）。')]}},

{w:'five', zh:'五',
 st:[['fīf','1000','古英文'],['fyve','600','中古英文'],['five','今天','英文']],
 al:'f=f ī=i f>v >e',
 a:{q:'一千年前的 five，最後一個字母是？', o:['f（fīf）','v','e','w'],
    l:['古英文 <b>fīf</b>：頭尾都是 f','後來寫成 <b>five</b>；fifteen、fifty 的 f 還在']},
 c:{m:'fiv[e]', q:'five 的哪一個字母<b>不唸</b>？', o:['字尾的 e','f','i','v'],
    was:'喬叟的時代（大約 630 年前），字尾 e 常常還會輕輕唸出來', lost:'大約 400 年前（莎士比亞的時代）就不唸了',
    l:['字尾 <b>e</b> 不唸','英文字不用 <b>v</b> 結尾，所以寫成 -ve']},
 src:{a:[C('oe'),ety('five','古英文 <b>fīf</b>；fifteen（fīftēne）、fifty（fīftig）的 f 就是這樣來的。'),C('gvs')],
      b:[ety('five','古英文 fīf ➜ 中古英文 fyve、five。')],
      c:[C('fe'),C('v')]}},

{w:'six', zh:'六',
 st:[['siex','1000','古英文'],['six','今天','英文']],
 al:'s=s ie>i x=x',
 a:{q:'一千年前的人怎麼寫「六」？', o:['siex、six 都有人寫','sex','zes','sechs'],
    l:['古英文就有人寫 <b>six</b>','一千年來<b>幾乎沒變</b>']},
 fun:{t:'x ＝ 兩個聲音', q:'six 的 <b>x</b> 唸成？', o:['k ＋ s','z','sh','不唸'],
    h:'<div class="evsp"><span class="two"><b>si<i class="evr">x</i></b><em>x ＝ <b>k ＋ s</b></em></span></div>',
    l:['一個字母 <b>x</b>，唸兩個聲音：<b>k ＋ s</b>','{{box}}、{{fox}} 也一樣']},
 src:{a:[C('oe'),ety('six','古英文 <b>siex、six、seox、sex</b>，好幾種寫法；拉丁文 sex、希臘文 hex 都是親戚。')],
      b:[ety('six','古英文 siex、six ➜ six。')],
      c:[E('x 唸 /ks/','Cambridge Dictionary「six」（US /sɪks/）','six 的 <b>x</b> 唸 <b>/ks/</b>：一個字母、兩個聲音。')]}},

{w:'seven', zh:'七',
 st:[['seofon','1000','古英文'],['seven','600','中古英文'],['seven','今天','英文']],
 al:'s=s eo>e f>v o>e n=n',
 a:{q:'古英文 <b>seofon</b> 的 f，其實唸成？', o:['v','f','p','不唸'],
    l:['f 夾在兩個母音中間，<b>本來就唸 v</b>','後來乾脆<b>寫成 v</b> ➜ <b>seven</b>']},
 fun:{t:'兩個音節', q:'seven 有幾個音節？', o:['2','1','3','4'],
    h:'<div class="evsp"><span class="two"><b><i class="evr">se</i>．<i class="evr">ven</i></b><em>se ＋ ven</em></span></div>',
    l:['兩個紅色母音 ＝ <b>兩個音節</b>：se．ven']},
 src:{a:[C('oe'),ety('seven','古英文 <b>seofon</b>；德文 sieben、荷蘭文 zeven。'),C('fv')],
      b:[ety('seven','古英文 seofon ➜ 中古英文 seven。')],
      c:[E('seven 兩個音節','Cambridge Dictionary「seven」（US /ˈsev.ən/）','se．ven：兩個母音的聲音 ＝ 兩個音節。')]}},

{w:'eight', zh:'八',
 st:[['eahta','1000','古英文'],['ehte','800','中古英文'],['eighte','600','中古英文'],['eight','今天','英文']],
 al:'e=e a>i h>gh t=t a>',
 a:{q:'eight 的 <b>gh</b>，最早是誰寫出來的？', o:['法國來的抄書人','維京人','羅馬人','維京人的國王'],
    l:['古英文 <b>eahta</b> 只寫一個 h','法國來的抄書人把這個聲音寫成 <b>gh</b>']},
 c:{m:'ei[gh]t', q:'eight 的哪兩個字母<b>不唸</b>？', o:['gh','ei','ht','et'],
    was:'以前 gh 唸成<b>喉嚨呼一口氣</b>的聲音，就像德文 acht 的 ch', lost:'大約 400 年前（1600 年左右）不唸了',
    cmp:['de-DE','acht','de','德文：八'], l:['德文 <b>acht</b>：ch 到今天<b>還在唸</b>','{{night}} 晚上 ＝ 德文 Nacht，一樣的密碼']},
 src:{a:[C('oe'),ety('eight','古英文 <b>eahta、æhta</b> ➜ <b>ehte</b>（大約 1200 年）➜ <b>eighte</b>（1300 年代後期）。')],
      b:[ety('eight','eahta ➜ ehte ➜ eighte ➜ eight。')],
      c:[C('gh'),E('德文還在唸','Duden「acht」','德文的「八」<b>acht</b>，ch 唸成喉嚨呼氣的聲音。')]}},

{w:'nine', zh:'九',
 st:[['nigon','1000','古英文'],['nyne','600','中古英文'],['nine','今天','英文']],
 al:'n=n i=i go> n=n >e',
 a:{q:'一千年前的 nine，中間多了什麼？', o:['go（nigon）','x','th','w'],
    l:['古英文 <b>nigon</b> 有兩個音節','中間的 <b>go</b> 唸掉了 ➜ <b>nyne ➜ nine</b>']},
 c:{m:'nin[e]', q:'nine 的哪一個字母<b>不唸</b>？', o:['字尾的 e','第一個 n','i','第二個 n'],
    was:'中古英文 <b>nyne</b>，字尾 e 常常還輕輕唸出來', lost:'大約 400 年前（莎士比亞的時代）就不唸了',
    l:['字尾 <b>e</b> 不唸','它讓 i 唸成 <b>ㄞ</b>（i 自己的名字）']},
 src:{a:[C('oe'),ety('nine','古英文 <b>nigon</b> ➜ 中古英文 <b>nyn、nyne</b> ➜ nine。')],
      b:[ety('nine','nigon ➜ nyne ➜ nine。')],
      c:[C('fe'),C('gvs')]}},

{w:'ten', zh:'十',
 st:[['tīen','1000','古英文'],['ten','今天','英文']],
 al:'t=t ī> e=e n=n',
 a:{q:'一千年前的「十」，跟今天比？', o:['差不多：tīen、tēn','完全不一樣','多了 th','是 zehn'],
    l:['古英文 <b>tīen</b>，也有人寫 <b>tēn</b>','一千年來<b>幾乎沒變</b>']},
 fun:{t:'-teen ＝ ten', q:'thir<b>teen</b> 的 teen 是什麼意思？', o:['十','年輕','眼淚','茶'],
    h:'<div class="evsp"><span class="two"><b>thir<i class="evr">teen</i></b><em>3 ＋ 10 ＝ 13</em></span><span class="two"><b>four<i class="evr">teen</i></b><em>4 ＋ 10 ＝ 14</em></span></div>',
    l:['<b>-teen</b> 就是 ten：thirteen ＝ 3 ＋ 10']},
 src:{a:[C('oe'),ety('ten','古英文 <b>tīen</b>（西撒克遜）、<b>tēn</b>（麥西亞）；德文 zehn。')],
      b:[ety('ten','tīen、tēn ➜ ten。')],
      c:[ety('-teen','<b>-teen</b> 就是 ten 的變形：thirteen ＝ three ＋ ten。')]}},

{w:'eleven', zh:'十一',
 st:[['endleofan','1000','古英文'],['elleven','600','中古英文'],['eleven','今天','英文']],
 al:'e=e nd>l l=l eo>e f>v a>e n=n',
 a:{q:'<b>endleofan</b> 最早的意思是？', o:['一，剩下來','很多個一','十個一','第十一'],
    l:['<b>en</b>（一）＋ <b>leofan</b>（剩下）','數完十根手指，<b>還剩一</b>']},
 fun:{t:'數完十，還剩一', q:'eleven 為什麼不叫 oneteen？', o:['它比 -teen 更老：意思是「剩下一」','因為 one 太短','因為 eleven 是法文','因為 oneteen 太難唸'],
    h:'<div class="evsp"><span class="two"><b>🖐🖐 ＋ ☝️</b><em>數完十，剩下一</em></span><span class="two"><b>eleven</b><em>剩下一</em></span><span class="two"><b>twelve</b><em>剩下二</em></span></div>',
    l:['<b>eleven ＝ 剩下一</b>、<b>twelve ＝ 剩下二</b>','13 以後才用 <b>-teen</b>']},
 src:{a:[C('oe'),ety('eleven','古英文 <b>enleofan、endleofan</b>，字面意思「<b>剩下一個</b>」（數完十以後）。')],
      b:[ety('eleven','endleofan ➜ enleven、elleven ➜ eleven。')],
      c:[ety('eleven','日耳曼語 <b>*ain-lif-</b>：ain（一）＋ lif（剩下）；立陶宛文也這樣數到 19。')]}},

{w:'twelve', zh:'十二',
 st:[['twelf','1000','古英文'],['twelve','600','中古英文'],['twelve','今天','英文']],
 al:'t=t w=w e=e l=l f>v >e',
 a:{q:'<b>twelf</b> 最早的意思是？', o:['二，剩下來','十個二','很多','兩個十'],
    l:['<b>twe</b>（二）＋ <b>lf</b>（剩下）','數完十根手指，<b>還剩二</b>']},
 c:{m:'twelv[e]', q:'twelve 的哪一個字母<b>不唸</b>？', o:['字尾的 e','w','l','v'],
    was:'中古英文 twelve 的字尾 e 常常還輕輕唸出來', lost:'大約 400 年前（莎士比亞的時代）就不唸了',
    l:['字尾 <b>e</b> 不唸','英文字不用 <b>v</b> 結尾，所以寫成 -ve']},
 src:{a:[C('oe'),ety('twelve','古英文 <b>twelf</b>，字面意思「<b>剩下二</b>」。')],
      b:[ety('twelve','twelf ➜ twelve。')],
      c:[C('fe'),C('v')]}},

/* ═════════════ 👀 三年級：Sight Words ═════════════ */
{w:'i', show:'I', zh:'我',
 st:[['ic','1000','古英文'],['i','850','中古英文'],['I','750','中古英文'],['I','今天','英文']],
 al:'i>I c>',
 a:{q:'「我」為什麼從小 i 變成大 I？', o:['小 i 太容易看漏','因為我最重要','國王規定','電腦改的'],
    l:['<b>ic</b> 的 c 不見了，只剩小小一個 <b>i</b>','太容易看漏 ➜ 抄書的人把它寫成<b>大寫 I</b>']},
 fun:{t:'德文、荷蘭文的「我」不大寫', q:'德文的「我」<b>ich</b>，要大寫嗎？', o:['不用','要','要，跟英文的 I 一樣','要，寫成 ICH'],
    h:'<div class="evsp"><span class="two"><b class="evr">I</b><em>英文：永遠大寫</em></span><span class="two"><b>ich</b><em>德文：不用大寫</em></span><span class="two"><b>ik</b><em>荷蘭文：不用大寫</em></span></div>',
    l:['德文、荷蘭文的「我」<b>都不大寫</b>','英文的 <b>I</b> 永遠大寫']},
 src:{a:[C('oe'),ety('I','古英文 <b>ic</b>；1100 年代中期在英格蘭北部縮成 <b>i</b>；<b>1200 年代中期</b>（大約 750 年前）開始寫成大寫，免得在手寫稿裡看漏。')],
      b:[ety('I','ic ➜ i ➜ I。')],
      c:[E('德文、荷蘭文不大寫','Duden「ich」；Van Dale「ik」','德文 ich、荷蘭文 ik 都是小寫。')]}},

{w:'my', show:'my', zh:'我的',
 st:[['mīn','1000','古英文'],['my','800','中古英文'],['my','今天','英文']],
 al:'m=m ī>y n>',
 a:{q:'<b>my</b> 是哪一個字變短的？', o:['mine','me','many','Monday'],
    l:['古英文 <b>mīn</b>（我的）','後面接東西的時候唸快了，<b>n 不見</b> ➜ <b>my</b>']},
 fun:{t:'my 和 mine 是一家人', q:'「這是<b>我的</b>書」和「書是<b>我的</b>」，英文用哪兩個字？', o:['my、mine','me、my','I、me','mine、me'],
    h:'<div class="evsp"><span class="two"><b>my book</b><em>我的書</em></span><span class="two"><b>It’s mine.</b><em>是我的。</em></span></div>',
    l:['後面有東西 ➜ <b>my</b>','後面沒有東西 ➜ <b>mine</b>']},
 src:{a:[C('oe'),ety('my','古英文 <b>mīn</b>；<b>1200 年左右</b>（大約 800 年前）放在子音開頭的字前面，唸短成 <b>my</b>。')],
      b:[ety('my','mīn ➜ my（mine 也留下來了）。')],
      c:[ety('mine','mine 和 my 本來是同一個字：my 是 mine 變短的。')]}},

{w:'you', show:'You', zh:'你',
 st:[['ēow','1000','古英文'],['yow','700','中古英文'],['you','今天','英文']],
 al:'ē>y o=o w>u',
 a:{q:'一千年前的 <b>ēow</b>，是什麼意思？', o:['你們','你','我','他'],
    l:['<b>ēow</b> 本來是「<b>你們</b>」','後來一個人、很多人，<b>都叫 you</b>']},
 c:{m:'y[o]u', q:'You 的哪一個字母<b>不唸</b>？', o:['o','Y','u','全部都唸'],
    was:'ou 是法國來的抄書人寫「ㄨ」的方法：兩個字母、一個聲音', lost:'今天只聽得到 <b>u</b> 的聲音',
    l:['<b>o</b> 不唸，只唸 u','{{soup}}、{{group}} 的 ou 也唸 ㄨ']},
 src:{a:[C('oe'),ety('you','古英文 <b>ēow</b>，本來是「<b>你們</b>」（受詞）；一個人的「你」是 <b>þū（thou）</b>。')],
      b:[ety('you','ēow ➜ yow、you。')],
      c:[E('ou 唸 /uː/','Cambridge Dictionary「you」（US /juː/）','you 唸 <b>/juː/</b>：ou 兩個字母，只唸一個 u 的聲音。')]}},

{w:'your', show:'Your', zh:'你的',
 st:[['ēower','1000','古英文'],['youre','700','中古英文'],['your','今天','英文']],
 al:'ē>y o=o we>u r=r',
 a:{q:'<b>your</b> 跟哪一個字是一家人？', o:['you','yes','yellow','year'],
    l:['古英文 <b>ēower</b> ＝ 你們的','<b>you ＋ r</b>：記住 your ＝ 你的']},
 c:{m:'y[o]ur', q:'Your 的哪一個字母<b>不唸</b>？', o:['o','Y','u','r'],
    was:'跟 you 一樣：ou 兩個字母、一個聲音', lost:'今天只聽得到 <b>u</b> 的聲音',
    l:['<b>o</b> 不唸','your ＝ <b>you ＋ r</b>']},
 src:{a:[C('oe'),ety('your','古英文 <b>ēower</b>（你們的）。')],
      b:[ety('your','ēower ➜ youre、your。')],
      c:[E('your 的唸法','Cambridge Dictionary「your」（US /jʊr/）','your 唸 /jʊr/：o 不出聲。')]}},

{w:'i-am', show:'I am', zh:'我 是',
 st:[['ic eom','1000','古英文'],['I am','700','中古英文'],['I’m','450','印刷時代'],['I am ＝ I’m','今天','英文']],
 al:'i>I c> eo>a m=m',
 a:{q:'<b>I’m</b> 的 ’ 是什麼意思？', o:['這裡少了一個字母 a','這裡要停一下','這是一個點','這是 I 的帽子'],
    l:['<b>I am</b> 說快一點 ＝ <b>I’m</b>','’ 告訴你：<b>這裡藏了一個 a</b>']},
 fun:{t:'’ 從哪裡來', q:'英文什麼時候開始用 ’？', o:['大約 470 年前，印刷工人','一千年前','大約 100 年前，打字機','大約 2000 年前，羅馬人'],
    h:'<div class="evsp"><span class="two"><b>I <i class="evr">a</i>m</b><em>完整</em></span><span class="ar">➜</span><span class="two"><b>I<i class="evr">’</i>m</b><em>a 藏起來</em></span></div>',
    l:['’ ＝ <b>這裡少了字母</b>','印刷工人大約 470 年前開始這樣寫']},
 src:{a:[C('oe'),ety('am','古英文 <b>eom</b>（麥西亞 eam、北方 am）＝ 我是。'),C('ap')],
      b:[ety('I','ic ➜ I；am 從北方的 <b>am</b> 來。')],
      c:[C('ap')]}},

{w:'you-are', show:'You are', zh:'你 是',
 st:[['gē earon','1000','古英文（北方）'],['ye are','600','中古英文'],['you are','今天','英文']],
 al:'gē>you ea>a ron>re',
 a:{q:'古英文北方人說的 <b>earon</b>，後來變成？', o:['are','ear','around','earn'],
    l:['北方的 <b>aron</b> 贏了，變成今天的 <b>are</b>','南方的 <b>sind</b>（德文 sind）後來不用了']},
 c:{m:'ar[e]', q:'are 的哪一個字母<b>不唸</b>？', o:['字尾的 e','a','r','全部都唸'],
    was:'are 唸 /ɑr/', lost:'字尾 e 沒有聲音',
    l:['<b>e</b> 不唸','You are ＝ <b>You’re</b>：’ 藏起 a']},
 src:{a:[C('oe'),ety('are','古英文北方 <b>aron</b>、麥西亞 <b>earun</b> ➜ are；南方的 sind 在 1200 年代初期消失（德文還說 sind）。')],
      b:[ety('are','earon、aron ➜ are。')],
      c:[E('are 的唸法','Cambridge Dictionary「are」（US /ɑːr/）','are 唸 /ɑr/，字尾 e 不出聲。')]}},

{w:'name', zh:'名字',
 st:[['nama','1000','古英文'],['name','600','中古英文'],['name','今天','英文']],
 al:'n=n a=a m=m a>e',
 a:{q:'一千年前的 <b>nama</b>，唸幾個音節？', o:['兩個：na-ma','一個','三個','四個'],
    l:['古英文 <b>nama</b>：na-ma，兩個音節','後來寫成 <b>name</b>']},
 c:{m:'nam[e]', q:'name 的哪一個字母<b>不唸</b>？', o:['字尾的 e','n','a','m'],
    was:'中古英文 name 唸 na-mə，字尾 e 輕輕唸出來', lost:'大約 400 年前（莎士比亞的時代）就不唸了',
    l:['字尾 <b>e</b> 不唸','它讓 a 唸成 <b>ㄝ</b>（a 自己的名字）']},
 src:{a:[C('oe'),ety('name','古英文 <b>nama、noma</b>（名字）。')],
      b:[ety('name','nama ➜ name。')],
      c:[C('fe'),C('gvs')]}},

{w:'is', zh:'是',
 st:[['is','1000','古英文'],['is','今天','英文']],
 al:'i=i s=s',
 a:{q:'一千年前的「是」怎麼寫？', o:['is','ist','es','si'],
    l:['古英文就寫 <b>is</b>','<b>一千多年都沒變</b>']},
 fun:{t:'s 唸 z', q:'is 的 <b>s</b> 唸成？', o:['z','s','sh','不唸'],
    h:'<div class="evsp"><span class="two"><b>i<i class="evr">s</i></b><em>s ＝ <b>/z/</b></em></span><span class="two"><b>is</b><em>荷蘭文：也寫 is</em></span></div>',
    l:['<b>is</b> 的 s 唸 <b>/z/</b>','荷蘭文的「是」也寫 <b>is</b>']},
 src:{a:[C('oe'),ety('is','古英文就是 <b>is</b>；德文 ist。')],
      b:[ety('is','is ➜ is（沒變）。')],
      c:[E('is 的唸法','Cambridge Dictionary「is」（US /ɪz/）','is 唸 <b>/ɪz/</b>：s 唸 z。'),E('荷蘭文','Van Dale「is」','荷蘭文的「是」也寫 is。')]}},

{w:'what', show:'What', zh:'什麼',
 st:[['hwæt','1000','古英文'],['what','850','中古英文'],['what','今天','英文']],
 al:'hw>wh æ>a t=t',
 a:{q:'古英文 <b>hwæt</b>，h 在哪裡？', o:['在 w 前面','在最後面','沒有 h','在 t 後面'],
    l:['古英文寫 <b>hw</b>：h 在前面','大約 850 年前改寫成 <b>wh</b>']},
 c:{m:'W[h]at', q:'What 的哪一個字母<b>不唸</b>？', o:['h','W','a','t'],
    was:'古英文 hw 真的唸出一個呼氣的 h', lost:'今天大多數人<b>不唸 h</b>，What 聽起來像 wat',
    l:['<b>h</b> 不唸','Who、Where、When、Why 都是 hw 家族']},
 src:{a:[C('oe'),ety('what','古英文 <b>hwæt</b>。'),C('hw')],
      b:[C('hw')],
      c:[E('What 的唸法','Cambridge Dictionary「what」（US /wɑːt/）','美式 what 唸 <b>/wɑːt/</b>：h 不出聲。'),C('hw')]}},

{w:'whats', show:'What’s', zh:'什麼 是',
 st:[['hwæt is','1000','古英文'],['what is','850','中古英文'],['what’s','450','印刷時代'],['What’s','今天','英文']],
 al:'hw>wh æ>a t=t i>’ s=s',
 a:{q:'<b>What’s</b> 的 ’ 藏起了哪一個字母？', o:['i','s','h','a'],
    l:['<b>What is</b> 說快一點 ＝ <b>What’s</b>','’ 藏起了 <b>is</b> 的 <b>i</b>']},
 c:{m:'W[h]at’s', q:'What’s 的哪一個字母<b>不唸</b>？', o:['h','W','t','s'],
    was:'古英文 hw 真的唸出 h', lost:'今天大多數人不唸 h',
    l:['<b>h</b> 不唸','’s ＝ is']},
 src:{a:[C('oe'),C('ap')],
      b:[C('hw'),C('ap')],
      c:[E('What’s ＝ What is','Cambridge Dictionary「what’s」','What’s 是 What is 的縮寫；美式 /wɑːts/。')]}},

{w:'how', show:'How', zh:'怎麼樣',
 st:[['hū','1000','古英文'],['how','600','中古英文'],['how','今天','英文']],
 al:'h=h ū>ow',
 a:{q:'一千年前的 <b>hū</b>，唸起來像？', o:['「呼」','「好」','「哈」','「黑」'],
    l:['古英文 <b>hū</b> 唸「<b>呼</b>」','法國來的抄書人把 ū 寫成 <b>ou、ow</b>']},
 fun:{t:'「呼」變成「好」', q:'hū（呼）後來為什麼唸 how（ㄏㄠ）？', o:['母音大搬家','法文的唸法','外國人唸錯','美國人改的'],
    h:'<div class="evsp"><span class="two"><b>hū</b><em>呼</em></span><span class="ar">➜</span><span class="two"><b>how</b><em>ㄏㄠ</em></span></div>',
    l:['大約 1400～1700 年，<b>ū（ㄨ）變成 ow（ㄠ）</b>','{{house}}（hūs）、{{now}}（nū）也一樣']},
 src:{a:[C('oe'),ety('how','古英文 <b>hū</b>。')],
      b:[ety('how','hū ➜ hou、how。')],
      c:[C('gvs')]}},

{w:'old', zh:'老的；…歲',
 st:[['ald','1000','古英文'],['old','700','中古英文'],['old','今天','英文']],
 al:'a>o l=l d=d',
 a:{q:'一千年前的 <b>ald</b>，哪個字母變了？', o:['a 變成 o','l 變成 r','d 變成 t','沒有變'],
    l:['古英文 <b>ald</b>（北方）、<b>eald</b>（南方）','a 慢慢唸成 <b>o</b> ➜ <b>old</b>']},
 fun:{t:'蘇格蘭還在說 auld', q:'蘇格蘭的新年歌《Auld Lang Syne》的 auld 是？', o:['old','all','owl','ouch'],
    h:'<div class="evsp"><span class="two"><b>auld</b><em>蘇格蘭：老的</em></span><span class="two"><b>old</b><em>英文：老的</em></span><span class="two"><b>alt</b><em>德文：老的</em></span></div>',
    l:['蘇格蘭的 <b>auld</b>，還留著以前的 a']},
 src:{a:[C('oe'),ety('old','古英文 <b>ald</b>（Anglian）、<b>eald</b>（西撒克遜）。')],
      b:[ety('old','ald ➜ old。')],
      c:[ety('auld','蘇格蘭的 <b>auld</b> 保留了古英文的母音。'),E('德文','Duden「alt」','德文的「老」是 alt。')]}},

{w:'how-old', show:'How old', zh:'幾歲',
 st:[['Hū eald eart þū?','1000','古英文'],['How old are you?','今天','英文']],
 al:'hū>how eald>old eart>are þū>you',
 a:{q:'How old are you? 一個字一個字換回一千年前的英文，會是？', o:['Hū eald eart þū?','Wie alt bist du?','What year you?','How many old?'],
    l:['<b>Hū</b> ＝ How、<b>eald</b> ＝ old、<b>eart</b> ＝ are、<b>þū</b> ＝ you','每一個字，一千年前<b>都找得到</b>']},
 fun:{t:'How old ＝ 多老', q:'How old 直接翻成中文是？', o:['多老','幾個老','老怎麼','老多'],
    h:'<div class="evsp"><span class="two"><b>How</b><em>多</em></span><span class="two"><b>old</b><em>老</em></span><span class="ar">＝</span><span class="two"><b>幾歲</b><em></em></span></div>',
    l:['<b>How old</b> ＝ 多老 ＝ <b>幾歲</b>']},
 src:{a:[C('oe'),ety('how','古英文 <b>hū</b> ＝ how。'),ety('old','古英文 <b>eald</b> ＝ old。'),ety('art','古英文 <b>þū eart</b> ＝ thou art（你是）；今天說 you are。')],
      b:[ety('how','hū ➜ how；eald ➜ old；þū ➜ thou（今天說 you）。')],
      c:[E('How old','Cambridge Dictionary「old」','How old are you? ＝ 你幾歲？')]}},

{w:'year', zh:'年',
 st:[['gēar','1000','古英文'],['yeer','750','中古英文'],['year','今天','英文']],
 al:'g>y ē=e a=a r=r',
 a:{q:'一千年前的 <b>gēar</b>，g 唸成？', o:['y','g','j','不唸'],
    l:['古英文寫 <b>g</b>，其實唸 <b>y</b>','大約 750 年前，法國來的抄書人改寫成 <b>y</b>']},
 c:{m:'ye[a]r', q:'year 的哪一個字母<b>不唸</b>？', o:['a','y','e','r'],
    was:'ea 兩個字母，只唸一個 ㄧ 的聲音', lost:'今天 year 唸 /jɪr/',
    cmp:['de-DE','Jahr','de','德文：年'], l:['<b>a</b> 不唸','德文 <b>Jahr</b>（年）的 J 也唸 y']},
 src:{a:[C('oe'),ety('year','古英文 <b>gēar</b>：這個 g 從來沒有唸成 g，<b>唸 y</b>；1200 年代初期開始改寫成 y。'),ety('yogh','古英文的 g 在 e、i 前面唸 y；中古英文用 ȝ（yogh），再換成 y。')],
      b:[ety('year','gēar ➜ yeer、yere ➜ year。')],
      c:[E('year 的唸法','Cambridge Dictionary「year」（US /jɪr/）','year 唸 /jɪr/：ea 只唸一個聲音。'),E('德文 Jahr','Duden「Jahr」','德文的「年」Jahr，J 唸 y。')]}},

{w:'years-old', show:'years old', zh:'…歲',
 st:[['gēar ＋ eald','1000','古英文'],['years old','今天','英文']],
 al:'g>y ē=e a=a r=r >s eald>old',
 a:{q:'<b>ten years old</b>，直接翻成中文是？', o:['十年那麼老','十個老年','老了十次','十點老'],
    l:['<b>ten years old</b> ＝ 十年那麼老 ＝ <b>十歲</b>','兩年以上，year 要加 <b>s</b>']},
 c:{m:'ye[a]rs old', q:'years 的哪一個字母<b>不唸</b>？', o:['a','y','r','s'],
    was:'ea 只唸一個 ㄧ 的聲音', lost:'今天 years 唸 /jɪrz/',
    l:['<b>a</b> 不唸','<b>s</b> 唸 z']},
 src:{a:[E('years old','Cambridge Dictionary「old」「year」','I’m ten years old. ＝ I’m ten.：years old 可以省略。')],
      b:[ety('year','gēar ➜ year；eald ➜ old。')],
      c:[E('years 的唸法','Cambridge Dictionary「year」（US /jɪrz/）','years 唸 /jɪrz/。')]}},

{w:'who', show:'Who', zh:'誰',
 st:[['hwā','1000','古英文'],['who','600','中古英文'],['who','今天','英文']],
 al:'hw>wh ā>o',
 a:{q:'古英文 <b>hwā</b> 後來變成？', o:['who','what','how','why'],
    l:['<b>hwā</b> 的 a 慢慢唸成 o ➜ <b>who</b>','two 也是這樣：twā ➜ two']},
 c:{m:'[W]ho', q:'Who 的哪一個字母<b>不唸</b>？', o:['W','h','o','全部都唸'],
    was:'以前 hw 一起唸', lost:'a 變成 o 以後，嘴巴已經嘟起來，<b>w 就被吃掉了</b>',
    l:['<b>W</b> 不唸：Who 唸 /huː/','{{two}} 的 w 也是這樣不見的']},
 src:{a:[C('oe'),ety('who','古英文 <b>hwā</b>（什麼人）。')],
      b:[C('hw')],
      c:[E('who、two 一起掉了 w','Wikipedia「Pronunciation of English ⟨wh⟩」','古英文 /hwɑː/ ➜ /hwoː/ ➜ /huː/，跟 /twɑː/ ➜ /twoː/ ➜ /tuː/（two）是同一條路。')]}},

{w:'where', show:'Where', zh:'哪裡',
 st:[['hwǣr','1000','古英文'],['where','850','中古英文'],['where','今天','英文']],
 al:'hw>wh ǣ>e r=r >e',
 a:{q:'古英文 <b>hwǣr</b> 的 hw 後來寫成？', o:['wh','hh','ww','w'],
    l:['<b>hwǣr</b> ➜ <b>where</b>','h 從前面<b>搬到後面</b>']},
 c:{m:'W[h]er[e]', q:'Where 的哪兩個字母<b>不唸</b>？', o:['h 和字尾 e','W 和 r','e 和 r','W 和 h'],
    was:'古英文 hw 真的唸出 h', lost:'今天大多數人不唸 h；字尾 e 也不唸',
    l:['<b>h</b>、字尾 <b>e</b> 不唸','{{here}}、{{there}}、{{where}}：三兄弟']},
 src:{a:[C('oe'),ety('where','古英文 <b>hwǣr</b>。'),C('hw')],
      b:[C('hw')],
      c:[E('where 的唸法','Cambridge Dictionary「where」（US /wer/）','美式 where 唸 /wer/。')]}},

{w:'when', show:'When', zh:'什麼時候',
 st:[['hwanne','1000','古英文'],['when','850','中古英文'],['when','今天','英文']],
 al:'hw>wh a>e n=n ne>',
 a:{q:'古英文 <b>hwanne</b> 變成 when，少了什麼？', o:['字尾的 ne','開頭的 h','w','全部'],
    l:['<b>hwanne</b> 唸短了 ➜ <b>when</b>','h 從前面搬到後面']},
 c:{m:'W[h]en', q:'When 的哪一個字母<b>不唸</b>？', o:['h','W','e','n'],
    was:'古英文 hw 真的唸出 h', lost:'今天大多數人不唸 h',
    l:['<b>h</b> 不唸','{{then}} 那時候 ↔ {{when}} 什麼時候']},
 src:{a:[C('oe'),ety('when','古英文 <b>hwanne、hwænne</b>。'),C('hw')],
      b:[C('hw')],
      c:[E('when 的唸法','Cambridge Dictionary「when」（US /wen/）','美式 when 唸 /wen/。')]}},

{w:'why', show:'Why', zh:'為什麼',
 st:[['hwȳ','1000','古英文'],['why','850','中古英文'],['why','今天','英文']],
 al:'hw>wh ȳ>y',
 a:{q:'古英文 <b>hwȳ</b>，唸起來像？', o:['「呼一」','「歪」','「喂」','「哇」'],
    l:['古英文 <b>hwȳ</b>：y 唸長長的「一」','母音大搬家以後，唸成 <b>why（ㄞ）</b>']},
 c:{m:'W[h]y', q:'Why 的哪一個字母<b>不唸</b>？', o:['h','W','y','全部都唸'],
    was:'古英文 hw 真的唸出 h', lost:'今天大多數人不唸 h',
    l:['<b>h</b> 不唸','Why? ➜ <b>Because</b>……']},
 src:{a:[C('oe'),ety('why','古英文 <b>hwȳ、hwī</b>。'),C('gvs')],
      b:[C('hw')],
      c:[E('why 的唸法','Cambridge Dictionary「why」（US /waɪ/）','美式 why 唸 /waɪ/。')]}},

/* ═════════════ 👨‍👩‍👧 四年級：家人 ═════════════ */
{w:'family', zh:'家人',
 st:[['familia','2000','拉丁文（羅馬人）'],['family','600','英文'],['family','今天','英文']],
 al:'f=f a=a m=m i=i l=l ia>y',
 a:{q:'<b>family</b> 是從哪裡來的？', o:['羅馬人的拉丁文','維京人','希臘文','德文'],
    l:['羅馬人的 <b>familia</b>：<b>連家裡幫忙做事的人都算</b>','大約 600 年前進入英文 ➜ <b>family</b>']},
 fun:{t:'ia 變成 y', q:'familia 的 <b>ia</b>，今天寫成？', o:['y','ie','a','i'],
    h:'<div class="evsp"><span class="two"><b>famil<i class="evno">ia</i></b><em>拉丁文</em></span><span class="ar">➜</span><span class="two"><b>famil<i class="evr">y</i></b><em>英文</em></span></div>',
    l:['字尾 <b>ia ➜ y</b>','三個音節：fa．mi．ly']},
 src:{a:[ety('family','<b>1400 年代初期</b>（大約 600 年前）進入英文，最早指「家裡的僕人」；拉丁文 <b>familia</b> ＝ 一家人連同僕人。')],
      b:[ety('family','拉丁文 familia ➜ 英文 family（ia 變成 y）。')],
      c:[ety('family','拉丁文 familia ➜ 英文 family。')]}},

{w:'parent', zh:'家長',
 st:[['parens','2000','拉丁文（羅馬人）'],['parent','900','法文'],['parent','600','英文'],['parent','今天','英文']],
 al:'p=p a=a r=r e=e n=n s>t',
 a:{q:'<b>parent</b> 最早的意思是？', o:['把孩子生下來的人','最老的人','會煮飯的人','隔壁的人'],
    l:['拉丁文 <b>parens</b> ＝ <b>生下孩子的人</b>','經過法文，大約 600 年前進入英文']},
 fun:{t:'一位還是兩位', q:'爸爸和媽媽「兩位」，英文是？', o:['parents','parent','parentes','parent two'],
    h:'<div class="evsp"><span class="two"><b>a parent</b><em>一位家長</em></span><span class="two"><b>parent<i class="evr">s</i></b><em>兩位以上</em></span></div>',
    l:['一位 <b>a parent</b>','兩位以上 <b>parents</b>']},
 src:{a:[ety('parent','拉丁文 <b>parens</b>（生下、產出）➜ 古法文 <b>parent</b>（1000 年代）➜ 英文（<b>1400 年代初期</b>成為一般名詞）。')],
      b:[ety('parent','parens ➜ parent。')],
      c:[E('一位還是很多位','Cambridge Dictionary「parent」','一位 a parent，兩位以上 parents。')]}},

{w:'mother', zh:'母親',
 st:[['mōdor','1000','古英文'],['moder','700','中古英文'],['mother','500','1500 年代'],['mother','今天','英文']],
 al:'m=m ō=o d>th o>e r=r',
 a:{q:'一千年前的 mother，中間是哪一個字母？', o:['d（mōdor）','th','t','b'],
    l:['古英文 <b>mōdor</b>：中間是 <b>d</b>','d 慢慢唸成 <b>th</b>，大約 500 年前拼法才跟上']},
 fun:{t:'d 變成 th', q:'下面哪一個字，也是 d 變成 th？', o:['father（fæder）','sister','son','aunt'],
    h:'<div class="evsp"><span class="two"><b>mō<i class="evno">d</i>or</b><em>古英文</em></span><span class="ar">➜</span><span class="two"><b>mo<i class="evr">th</i>er</b><em>今天</em></span><span class="two"><b>fæ<i class="evno">d</i>er ➜ fa<i class="evr">th</i>er</b><em>爸爸也一樣</em></span></div>',
    l:['<b>d ➜ th</b>：mother、father 一起變']},
 src:{a:[C('oe'),ety('mother','古英文 <b>mōdor</b>；-th- 的拼法<b>1500 年代初期</b>才出現，唸法可能更早。')],
      b:[ety('mother','mōdor ➜ moder ➜ mother。')],
      c:[ety('father','father 也一樣：fæder ➜ fader ➜ father（1500 年代拼法跟上唸法）。')]}},

{w:'father', zh:'父親',
 st:[['fæder','1000','古英文'],['fader','700','中古英文'],['father','500','1500 年代'],['father','今天','英文']],
 al:'f=f æ>a d>th e=e r=r',
 a:{q:'一千年前的 father，中間是哪一個字母？', o:['d（fæder）','th','t','v'],
    l:['古英文 <b>fæder</b>：中間是 <b>d</b>','d 慢慢唸成 <b>th</b>，1500 年代拼法才跟上']},
 fun:{t:'æ 是什麼字母？', q:'fæder 的 <b>æ</b>，是哪兩個字母黏在一起？', o:['a ＋ e','o ＋ e','a ＋ i','e ＋ e'],
    h:'<div class="evsp"><span class="two"><b class="evr">æ</b><em>a ＋ e 黏在一起</em></span><span class="ar">➜</span><span class="two"><b>a</b><em>今天只剩 a</em></span></div>',
    l:['古英文的 <b>æ</b> ＝ a、e 黏在一起的字母','今天的 father 只留下 <b>a</b>']},
 src:{a:[C('oe'),ety('father','古英文 <b>fæder</b>；-th- 的拼法 1400 年代出現，<b>1500 年代</b>拼法才跟上唸法。')],
      b:[ety('father','fæder ➜ fader ➜ father。')],
      c:[E('æ（ash）','Wikipedia「Æ」','古英文的字母 <b>æ</b>（ash），由 a、e 合成。')]}},

{w:'brother', zh:'哥哥、弟弟',
 st:[['brōþor','1000','古英文'],['brother','500','印刷時代'],['brother','今天','英文']],
 al:'b=b r=r ō=o þ>th o>e r=r',
 a:{q:'<b>brōþor</b> 的 þ，為什麼變成 th？', o:['印刷機沒有 þ 這個字','寫錯了','維京人不會寫 þ','þ 太難唸'],
    l:['1476 年英國第一台印刷機<b>沒有 þ</b>','就用 <b>th</b> 代替 ➜ <b>brother</b>']},
 fun:{t:'Ye Olde ＝ The Old', q:'英國老店招牌寫「<b>Ye</b> Olde Shop」，Ye 其實是？', o:['The','You','Yes','Yellow'],
    h:'<div class="evsp"><span class="two"><b><i class="evr">þ</i>e</b><em>手寫</em></span><span class="ar">➜</span><span class="two"><b><i class="evr">y</i>e</b><em>印刷機沒有 þ，拿 y 代替</em></span><span class="ar">＝</span><span class="two"><b>the</b><em></em></span></div>',
    l:['þ 長得像 y，印刷工人就拿 <b>y</b> 代替','Ye Olde ＝ <b>The Old</b>']},
 src:{a:[C('oe'),ety('brother','古英文 <b>brōþor</b>。'),C('thorn')],
      b:[C('thorn')],
      c:[E('Ye Olde','Wikipedia「Ye olde」「Thorn (letter)」','印刷時用 y 代替 þ，所以寫成 ye，<b>一直都唸 the</b>。')]}},

{w:'sister', zh:'姊姊、妹妹',
 st:[['sweostor','1000','古英文'],['systir','1100','維京人的古北歐語'],['sister','700','中古英文'],['sister','今天','英文']],
 al:'s=s weo>i s=s t=t o>e r=r',
 a:{q:'<b>sister</b> 這個樣子，是誰帶來的？', o:['坐船來的維京人','法國國王','德國人','羅馬人'],
    l:['英國人說 <b>sweostor</b>，維京人說 <b>systir</b>','兩邊住在一起，英文<b>跟著維京人</b>說 sister']},
 fun:{t:'維京人住在哪裡', q:'英國很多地名結尾是 <b>-by</b>（Whitby、Derby），-by 是維京話的？', o:['村子','河','山','城堡'],
    h:'<div class="evsp"><span class="two"><b>Whit<i class="evr">by</i></b><em>白色的村子</em></span><span class="two"><b>Der<i class="evr">by</i></b><em>鹿的村子</em></span></div>',
    l:['<b>-by</b> ＝ 維京話的「村子」','維京人住過的地方，地名到今天還在']},
 src:{a:[C('oe'),ety('sister','古英文 <b>sweostor、swustor</b>；中古英文的 <b>sister、syster</b> 是受古北歐語 <b>systir</b> 影響。'),E('維京人住進英格蘭','Wikipedia「Danelaw」','<b>800～900 年代</b>，維京人住進英格蘭東北部（丹麥區 Danelaw）。')],
      b:[ety('sister','sweostor ＋ 古北歐語 systir ➜ sister。')],
      c:[E('-by ＝ 村子','Wikipedia「Whitby」「Derby」「Danelaw」','古北歐語 <b>býr</b> ＝ 農莊、村子：Whitby（白色的村子）、Derby（鹿的村子）。')]}},

{w:'son', zh:'兒子',
 st:[['sunu','1000','古英文'],['sone','700','中古英文'],['son','今天','英文']],
 al:'s=s u>o n=n u>',
 a:{q:'<b>sunu</b> 的 u，為什麼寫成 o？', o:['u 和 n 連在一起太難認','寫錯了','o 比較好聽','古時候 o 和 u 唸一樣'],
    l:['手寫的 u、n、m 都是一根一根的直線，<b>連在一起分不出來</b>','抄書的人把 u 改寫成 <b>o</b>，<b>聲音沒變</b>']},
 fun:{t:'son ＝ sun', q:'哪一個字跟 son 唸起來<b>一模一樣</b>？', o:['sun 太陽','soon 很快','song 歌','sing 唱'],
    h:'<div class="evsp"><span class="two"><b>s<i class="evr">o</i>n</b><em>兒子</em></span><span class="ar">＝</span><span class="two"><b>s<i class="evr">u</i>n</b><em>太陽</em></span></div>',
    l:['<b>son ＝ sun</b>：唸法一模一樣','{{love}}、{{come}}、{{Monday}} 的 o 也唸 ㄜ']},
 src:{a:[C('oe'),ety('son','古英文 <b>sunu</b>。'),C('so')],
      b:[C('so')],
      c:[E('son、sun 同音','Cambridge Dictionary「son」「sun」（US /sʌn/）','兩個字都唸 /sʌn/。')]}},

{w:'daughter', zh:'女兒',
 st:[['dohtor','1000','古英文'],['doughter','700','中古英文'],['daughter','500','1500 年代'],['daughter','今天','英文']],
 al:'d=d o>au h>gh t=t o>e r=r',
 a:{q:'<b>dohtor</b> 的 h，後來寫成？', o:['gh','th','ch','f'],
    l:['古英文 <b>dohtor</b> 只寫一個 h','法國來的抄書人寫成 <b>gh</b>；1500 年代變成 daughter']},
 c:{m:'dau[gh]ter', q:'daughter 的哪兩個字母<b>不唸</b>？', o:['gh','au','te','er'],
    was:'以前 gh 唸成<b>喉嚨呼一口氣</b>的聲音，像德文 Tochter 的 ch', lost:'大約 400 年前（1600 年左右）不唸了',
    cmp:['de-DE','Tochter','de','德文：女兒'], l:['德文 <b>Tochter</b>：ch 到今天<b>還在唸</b>','荷蘭文 <b>dochter</b> 也一樣']},
 src:{a:[C('oe'),ety('daughter','古英文 <b>dohtor</b> ➜ 中古英文 <b>doughter</b>；今天的拼法 <b>1500 年代</b>在英格蘭南部定下來。')],
      b:[ety('daughter','dohtor ➜ doughter ➜ daughter。')],
      c:[C('gh'),E('德文、荷蘭文還在唸','Duden「Tochter」；Van Dale「dochter」','ch 還唸成喉嚨呼氣的聲音。')]}},

{w:'grandfather', zh:'爺爺',
 st:[['ealdfæder','1000','古英文：老的父親'],['grandfather','600','1400 年代'],['grandfather','今天','英文']],
 al:'eald>grand f=f æ>a d>th e=e r=r',
 a:{q:'一千年前的「爺爺」，英文說？', o:['ealdfæder（老的父親）','grandpa','Opa','papi'],
    l:['古英文 <b>ealdfæder</b> ＝ <b>老的</b>父親','大約 600 年前學法文 grand-père，改說 <b>grandfather</b>']},
 fun:{t:'grand ＝ 大', q:'<b>grand</b> 的意思是？', o:['大','老','好','爺爺'],
    h:'<div class="evsp"><span class="two"><b class="evr">grand</b><em>大（法文）</em></span><span class="ar">＋</span><span class="two"><b>father</b><em>父親</em></span><span class="ar">＝</span><span class="two"><b>大的父親</b><em>爺爺</em></span></div>',
    l:['<b>grand ＝ 大</b>（Grand Canyon 大峽谷）','grandfather ＝ 大一輩的父親']},
 src:{a:[C('oe'),ety('grandfather','<b>1400 年代初期</b>，學法文 grand-père 造出來，取代了古英文 <b>ealdefæder</b> 和 grandsire。'),C('fr')],
      b:[ety('grandfather','ealdfæder ➜ grandfather。')],
      c:[ety('grand-','法文 grand ＝ 大。')]}},

{w:'grandmother', zh:'奶奶',
 st:[['ealdmōdor','1000','古英文：老的母親'],['grandmother','600','1400 年代'],['grandmother','今天','英文']],
 al:'eald>grand m=m ō=o d>th o>e r=r',
 a:{q:'一千年前的「奶奶」，英文說？', o:['ealdmōdor（老的母親）','grandma','Oma','mamie'],
    l:['古英文 <b>ealdmōdor</b> ＝ <b>老的</b>母親','大約 600 年前學法文，改說 <b>grandmother</b>']},
 fun:{t:'grand ＝ 大', q:'grandmother 可以說得更短嗎？', o:['grandma','gma','mother grand','granny mom'],
    h:'<div class="evsp"><span class="two"><b>grandmother</b><em>奶奶</em></span><span class="ar">＝</span><span class="two"><b>grandma</b><em>口語</em></span></div>',
    l:['<b>grand ＝ 大</b>','口語說 <b>grandma</b>']},
 src:{a:[C('oe'),ety('grandmother','<b>1400 年代初期</b>出現，取代古英文 <b>ealdmōdor</b> 和 grandam。'),C('fr')],
      b:[ety('grandmother','ealdmōdor ➜ grandmother。')],
      c:[ety('grandma','grandma 是 grandmother 的口語。')]}},

{w:'uncle', zh:'叔叔、舅舅',
 st:[['avunculus','2000','拉丁文（羅馬人）'],['oncle','900','法文'],['uncle','700','英文'],['uncle','今天','英文']],
 al:'avunc>unc ulus>le',
 a:{q:'羅馬人的 <b>avunculus</b>，最早只能叫誰？', o:['媽媽的兄弟','爸爸的兄弟','爺爺','鄰居'],
    l:['<b>avunculus</b> ＝ 媽媽的兄弟（舅舅）','經過法文 oncle，大約 700 年前進入英文 ➜ <b>uncle</b>']},
 c:{m:'uncl[e]', q:'uncle 的哪一個字母<b>不唸</b>？', o:['字尾的 e','u','c','l'],
    was:'-cle 唸成 /kəl/：母音的聲音在 l 身上', lost:'字尾 e 沒有聲音',
    l:['字尾 <b>e</b> 不唸','叔叔伯伯舅舅姑丈姨丈，<b>全部都是 uncle</b>']},
 src:{a:[ety('uncle','<b>1300 年左右</b>（大約 700 年前）從法文 <b>oncle</b> 進入英文；拉丁文 <b>avunculus</b> ＝ 媽媽的兄弟（爸爸的兄弟叫 patruus）。'),C('fr')],
      b:[ety('uncle','avunculus ➜ oncle ➜ uncle。')],
      c:[E('uncle 的唸法','Cambridge Dictionary「uncle」（US /ˈʌŋ.kəl/）','uncle 唸 /ˈʌŋkəl/，字尾 e 不出聲。')]}},

{w:'aunt', zh:'阿姨、姑姑',
 st:[['amita','2000','拉丁文（羅馬人）'],['ante','900','法文'],['aunte','700','英文'],['aunt','今天','英文']],
 al:'a=a mi>u t=t a>',
 a:{q:'羅馬人的 <b>amita</b>，最早只能叫誰？', o:['爸爸的姊妹','媽媽的姊妹','奶奶','女老師'],
    l:['<b>amita</b> ＝ 爸爸的姊妹（姑姑）','經過法文，大約 700 年前進入英文 ➜ <b>aunt</b>']},
 c:{m:'a[u]nt', q:'aunt（美式）的哪一個字母<b>不唸</b>？', o:['u','a','n','t'],
    was:'au 兩個字母，美式只唸 ㄝ（像 ant）', lost:'美式 aunt 唸 /ænt/',
    l:['美式：<b>u</b> 不唸','阿姨姑姑舅媽嬸嬸，<b>全部都是 aunt</b>']},
 src:{a:[ety('aunt','<b>1300 年左右</b>從法文 <b>aunte、ante</b> 進入英文；拉丁文 <b>amita</b> ＝ 爸爸的姊妹。'),C('fr')],
      b:[ety('aunt','amita ➜ ante ➜ aunte ➜ aunt。')],
      c:[E('aunt 的美式唸法','Cambridge Dictionary「aunt」（US /ænt/）','美式 aunt 唸 /ænt/。')]}},

{w:'cousin', zh:'堂表兄弟姊妹',
 st:[['consobrinus','2000','拉丁文（羅馬人）'],['cosin','900','法文'],['cosin','700','英文'],['cousin','今天','英文']],
 al:'co=co ns>u ob> r> i=i nus>n',
 a:{q:'羅馬人的 <b>consobrinus</b>，最早只能叫誰？', o:['媽媽的姊妹的小孩','叔叔的小孩','哥哥的小孩','鄰居的小孩'],
    l:['<b>con</b>（一起）＋ <b>sobrinus</b>（媽媽那邊的表親）','經過法文 cosin，大約 700 年前進入英文']},
 c:{m:'c[o]usin', q:'cousin 的哪一個字母<b>不唸</b>？', o:['o','c','u','s'],
    was:'ou 兩個字母，只唸一個 ㄜ', lost:'cousin 唸 /ˈkʌzən/',
    l:['<b>o</b> 不唸','堂哥表妹……<b>全部都是 cousin</b>']},
 src:{a:[ety('cousin','<b>1300 年左右</b>從法文 <b>cosin</b> 進入英文；拉丁文 <b>consobrinus</b> 原本是「媽媽的姊妹的兒子」。'),C('fr')],
      b:[ety('cousin','consobrinus ➜ cosin ➜ cousin。')],
      c:[E('cousin 的唸法','Cambridge Dictionary「cousin」（US /ˈkʌz.ən/）','cousin 唸 /ˈkʌzən/：o 不出聲。')]}},

{w:'nephew', zh:'姪子、外甥',
 st:[['nepos','2000','拉丁文（羅馬人）'],['neveu','900','法文'],['nevew','700','英文'],['nephew','550','1400 年代'],['nephew','今天','英文']],
 al:'n=n e=e v>ph e=e u>w',
 a:{q:'nephew 的 <b>ph</b>，是怎麼來的？', o:['學拉丁文 nepos 的 p 改寫','一直都是 ph','打錯字','希臘人送的'],
    l:['大約 700 年前從法文 <b>neveu</b> 進來，寫成 <b>nevew</b>','1400 年代學拉丁文 nepos，改寫成 <b>ph</b>']},
 fun:{t:'ph 以前唸 v', q:'以前的英國人把 nephew 唸成？', o:['ne-vew','ne-few','nep-hew','ne-pew'],
    h:'<div class="evsp"><span class="two"><b>ne<i class="evr">v</i>ew</b><em>以前唸 v</em></span><span class="ar">➜</span><span class="two"><b>ne<i class="evr">ph</i>ew</b><em>今天唸 f</em></span></div>',
    l:['以前 <b>ph</b> 唸 <b>v</b>','後來大家<b>照拼字唸</b>，變成 f']},
 src:{a:[ety('nephew','<b>1300 年左右</b>從法文 <b>neveu</b> 進入英文；拉丁文 <b>nepos</b> ＝ 孫子、姪子。'),E('ph 的拼法','Languagehat「Nephew」；Collins「nephew」發音','<b>1400 年代</b>開始學拉丁文 nepos 寫成 -ph-；舊唸法是 /v/，後來大多數人改照拼字唸 /f/。')],
      b:[ety('nephew','nepos ➜ neveu ➜ nevew ➜ nephew。')],
      c:[E('ph 以前唸 v','Collins Dictionary「nephew」','英式有 /ˈnevjuː/ 和 /ˈnefjuː/ 兩種唸法；1948 年以後出生的人九成以上唸 /f/。')]}},

{w:'niece', zh:'姪女、外甥女',
 st:[['neptis','2000','拉丁文（羅馬人）'],['niece','900','法文'],['nece','700','英文'],['niece','今天','英文']],
 al:'n=n ep>ie t>c is>e',
 a:{q:'羅馬人的 <b>neptis</b>，本來是？', o:['孫女','阿姨','奶奶','女老師'],
    l:['<b>neptis</b> ＝ 孫女','經過法文，大約 700 年前進入英文 ➜ <b>niece</b>']},
 c:{m:'n[i]ec[e]', q:'niece 的哪兩個字母<b>不唸</b>？', o:['i 和字尾 e','n 和 c','第一個 e 和 c','全部都唸'],
    was:'ie 兩個字母，只唸一個長長的 ㄧ', lost:'niece 唸 /niːs/',
    l:['<b>i</b>、字尾 <b>e</b> 不唸','niece ↔ nephew：一對']},
 src:{a:[ety('niece','<b>1300 年左右</b>寫成 <b>nece</b> 進入英文；法文 niece ← 拉丁文 <b>neptis</b>（孫女）。'),C('fr')],
      b:[ety('niece','neptis ➜ niece ➜ nece ➜ niece。')],
      c:[E('niece 的唸法','Cambridge Dictionary「niece」（US /niːs/）','niece 唸 /niːs/。')]}},

{w:'husband', zh:'丈夫',
 st:[['húsbóndi','1100','維京人的古北歐語'],['hūsbōnda','1000','古英文'],['husband','今天','英文']],
 al:'h=h ú>u s=s b=b ó>a nd=nd i>',
 a:{q:'<b>husband</b> 裡面藏著哪一個東西？', o:['house 房子','horse 馬','hat 帽子','hand 手'],
    l:['<b>hūs</b> ＝ house（房子）＋ <b>bōnda</b> ＝ 住的人','husband ＝ <b>一家之主</b>']},
 fun:{t:'hus ＝ house', q:'古英文 hūs（房子）後來變成？', o:['house','horse','hose','who'],
    h:'<div class="evsp"><span class="two"><b class="evr">hūs</b><em>古英文：房子</em></span><span class="ar">➜</span><span class="two"><b>house</b><em>房子</em></span><span class="two"><b>Haus</b><em>德文：房子</em></span></div>',
    l:['<b>hūs ➜ house</b>','德文到今天還說 <b>Haus</b>']},
 src:{a:[ety('husband','古英文 <b>hūsbōnda</b>（一家之主），可能來自古北歐語 <b>húsbóndi</b> ＝ hús（房子）＋ bóndi（住的人）；1200 年代後期取代 wer 成為「丈夫」。')],
      b:[ety('husband','hūsbōnda ➜ housbond ➜ husband。')],
      c:[ety('house','古英文 hūs ➜ house；德文 Haus。')]}},

{w:'wife', zh:'太太',
 st:[['wīf','1000','古英文'],['wyf','700','中古英文'],['wife','今天','英文']],
 al:'w=w ī=i f=f >e',
 a:{q:'古英文 <b>wīf</b>，指的是誰？', o:['每一個女生','只有媽媽','只有皇后','每一個小孩'],
    l:['<b>wīf</b> ＝ 女人','後來才變成「<b>太太</b>」']},
 c:{m:'wif[e]', q:'wife 的哪一個字母<b>不唸</b>？', o:['字尾的 e','w','i','f'],
    was:'古英文 wīf <b>沒有 e</b>；今天的 e 不發音，提醒你 i 唸 ㄞ', lost:'母音大搬家（1400～1700 年）：wīf（ㄨㄧ）➜ wife（ㄨㄞ）',
    l:['字尾 <b>e</b> 不唸','它提醒你：i 唸 <b>ㄞ</b>']},
 src:{a:[C('oe'),ety('wife','古英文 <b>wīf</b> ＝ 女人；後期古英文才有「太太」的意思。')],
      b:[ety('wife','wīf ➜ wyf ➜ wife。')],
      c:[C('gvs')]}},

/* ═════════════ 💼 四年級：職業 ═════════════ */
{w:'student', zh:'學生',
 st:[['studens','2000','拉丁文（羅馬人）'],['estudiant','900','法文'],['studient','650','英文'],['student','今天','英文']],
 al:'stud=stud i> ent=ent',
 a:{q:'<b>student</b> 最早的意思是？', o:['很用功讀書的人','小孩','穿制服的人','坐在教室的人'],
    l:['拉丁文 <b>studens</b> ＝ 很用功的人','大約 650 年前進入英文 ➜ <b>student</b>']},
 fun:{t:'study ＋ ent', q:'student 跟哪一個字是一家人？', o:['study 讀書','stand 站','stone 石頭','stop 停'],
    h:'<div class="evsp"><span class="two"><b class="evr">stud</b><em>用功</em></span><span class="two"><b>study</b><em>讀書</em></span><span class="two"><b>student</b><em>學生</em></span></div>',
    l:['<b>study</b> 讀書 ➜ <b>student</b> 學生']},
 src:{a:[ety('student','<b>1300 年代後期</b>寫成 <b>studient</b>，從古法文 estudiant；拉丁文 studium ＝ 用功、熱心。')],
      b:[ety('student','studens ➜ estudiant ➜ studient ➜ student。')],
      c:[ety('study','study 和 student 同一個拉丁字根 stud-。')]}},

{w:'teacher', zh:'老師',
 st:[['tǣcan','1000','古英文：教'],['techer','680','中古英文'],['teacher','今天','英文']],
 al:'t=t ǣ>ea c>ch an>er',
 a:{q:'teacher 的 <b>teach</b>，一千年前的意思是？', o:['指給你看','打分數','說故事','寫黑板'],
    l:['古英文 <b>tǣcan</b> ＝ <b>指給你看</b>、教','teach ＋ er ＝ <b>teacher</b>（教的人）']},
 fun:{t:'-er ＝ 做這件事的人', q:'teach 教 ➜ teacher 老師。那 farm 農場 ➜ ？', o:['farmer 農夫','farming','farms','farmy'],
    h:'<div class="evsp"><span class="two"><b>teach<i class="evr">er</i></b><em>教的人</em></span><span class="two"><b>farm<i class="evr">er</i></b><em>種田的人</em></span></div>',
    l:['<b>-er</b> ＝ 做這件事的人']},
 src:{a:[C('oe'),ety('teacher','古英文 <b>tǣcan</b>（指給人看、教）；<b>techer</b> 在 <b>1300 年代中期</b>出現。')],
      b:[ety('teach','tǣcan ➜ tēchen ➜ teach。')],
      c:[ety('teacher','teach ＋ -er（做這件事的人）。')]}},

{w:'doctor', zh:'醫生',
 st:[['doctor','2000','拉丁文：老師'],['doctour','700','英文'],['doctor','450','英文：醫生'],['doctor','今天','英文']],
 al:'d=d o=o c=c t=t o=o r=r',
 a:{q:'<b>doctor</b> 在拉丁文本來是？', o:['老師','醫生','護士','病人'],
    l:['拉丁文 <b>doctor</b> ＝ <b>老師</b>','大約 450 年前，「醫生」的意思才普遍']},
 fun:{t:'拼法兩千年沒變', q:'羅馬人的 doctor 跟今天的 doctor 比？', o:['拼法一樣，意思變了','拼法、意思都一樣','完全不一樣','只差一個字母'],
    h:'<div class="evsp"><span class="two"><b>doctor</b><em>羅馬：老師</em></span><span class="ar">➜</span><span class="two"><b>doctor</b><em>今天：醫生</em></span></div>',
    l:['拼法<b>一樣</b>','意思從「老師」變成「<b>醫生</b>」']},
 src:{a:[ety('doctor','<b>1300 年左右</b>進入英文（doctour）；拉丁文 doctor ＝ 老師（docere 教）。「醫生」的意思 1400 年左右出現，<b>1500 年代後期</b>才普遍。')],
      b:[ety('doctor','doctor ➜ doctour ➜ doctor。')],
      c:[ety('doctor','同一個字，意思從老師變成醫生。')]}},

{w:'farmer', zh:'農夫',
 st:[['firma','1000','中世紀拉丁文：固定付的錢'],['fermer','650','英文：收稅的人'],['farmer','430','英文：種田的人'],['farmer','今天','英文']],
 al:'f=f e>a r=r m=m e=e r=r',
 a:{q:'<b>farmer</b> 最早的意思是？', o:['收稅、收租金的人','種田的人','養牛的人','賣菜的人'],
    l:['大約 650 年前 <b>fermer</b> ＝ <b>收稅、收租金的人</b>','大約 430 年前（1590 年代）才變成「<b>種田的人</b>」']},
 fun:{t:'farm ＝ 固定付的錢', q:'farm 最早是什麼意思？', o:['固定付的租金','田','牛','房子'],
    h:'<div class="evsp"><span class="two"><b>firma</b><em>固定付的錢</em></span><span class="ar">➜</span><span class="two"><b>farm</b><em>租來的田</em></span><span class="ar">➜</span><span class="two"><b>farmer</b><em>種田的人</em></span></div>',
    l:['<b>租一塊田</b>，每年<b>固定付錢</b> ➜ farm']},
 src:{a:[ety('farmer','<b>1300 年代後期</b>：fermer ＝ 收稅的人（古法文 fermier）；種田的意思 <b>1590 年代</b>才出現。')],
      b:[ety('farm','中世紀拉丁文 <b>firma</b>（固定付的錢）➜ farm。')],
      c:[ety('farm','firma ➜ ferme ➜ farm。')]}},

{w:'nurse', zh:'護理師',
 st:[['nutricia','2000','拉丁文：餵奶的人'],['norice','800','英文：奶媽'],['nurse','440','英文：照顧病人的人'],['nurse','今天','英文']],
 al:'nu=nu tri>r cia>se',
 a:{q:'<b>nurse</b> 最早的意思是？', o:['餵寶寶喝奶的人','醫生','老師','廚師'],
    l:['拉丁文 <b>nutricia</b> ＝ 餵奶、照顧小孩的人','大約 440 年前才變成「<b>照顧病人的人</b>」']},
 fun:{t:'nurse ＝ nourish（養）', q:'nurse 跟哪一個字是一家人？', o:['nutrition 營養','nut 堅果','number 數字','nose 鼻子'],
    h:'<div class="evsp"><span class="two"><b class="evr">nu</b>rse<em>照顧的人</em></span><span class="two"><b class="evr">nu</b>trition<em>營養</em></span></div>',
    l:['<b>nurse</b>、<b>nutrition</b>：都從拉丁文 nutrire（餵養）來']},
 src:{a:[ety('nurse','<b>1200 年左右</b>寫成 <b>norice</b>（奶媽）；拉丁文 nutricia ← nutrire（餵奶）。「照顧病人」的意思 <b>1580 年代</b>才有。')],
      b:[ety('nurse','nutricia ➜ norrice ➜ norice ➜ nurse。')],
      c:[ety('nourish','nurse、nourish、nutrition 都來自拉丁文 nutrire（餵養）。')]}}
];

module.exports = { EVO, S };
