/* review1/_data.js — Review 1 物品／活動單字卡的唯一真相來源（三、四年級共用；使用者 2026-10-01、2026-10-02 指定）
 *
 * 名單、類別、證據數字：**只能照** sentences/review1_單字名單_查證.md 那一列的備註（已打開核對的出處），
 * 不再上網找人氣證據、不改名單。字源／字的結構另外查證（2026-10-02 逐條打開 Etymonline、Merriam-Webster、
 * Cambridge、維基百科、教育部臺灣台語常用詞辭典），每一條附出處；查不到的字就不放第 2 條。
 *
 * 一個字一筆：
 *   f    檔名（片語用 - 連起來：play-basketball.html）
 *   en   英文（片語照查證檔的寫法，例：play with LEGO）
 *   zh   中文（動詞片語：動詞和名詞中間空一格，例：打 籃球；使用者 2026-10-02）
 *   g    組別：i1 物品1、i2 物品2、a1 活動1、a2 活動2
 *   cat  類別（查證檔那一格）
 *   ic   幕① 的大圖示（emoji 或 _icons.js 自己畫的 SVG）
 *   tk   逐字：[英文, 中文（'' ＝ 下面空白）, 圖示（'' ＝ 沒有）]；品牌名整個當一格
 *   pt   幕② 的「字的結構」一行（{{單字}} ＝ 可以點來聽；只放 et 查得到的）
 *   ex   幕③ 的整句中文（不空格）
 *   ev   出處第 1 條：人氣證據（小圖表）。bars 一列一件事：{p:%} 長條、{rk:名次} 獎牌、{tp:1} 老師選的字、{tx:一句話}
 *   et   出處第 2 條：字源／結構。eq ＝ [圖示, 英文, 中文] 一格一格；ch:1 ＝ 一站一站旅行（➜），不寫 ＝ 組合（＋ … ＝）
 */
const { ICON: I } = require('./_icons');
const WF = require('../words/_world').flag;

/* ── 音標／音節（跟 words/_phonics.js 的 RAW 同一種寫法；build 會檢查字母接得回去、一個音節一個母音）──
 * 音標：Cambridge Dictionary 美式（第一個美式標音）；KK：台灣課本標法。品牌名：Roblox、Mario 照維基百科，
 * Minecraft、Splatoon、Beyblade 辭典沒有收，照組成的字（mine＋craft…）。
 * 音節（使用者 2026-10-02 指定，全站一樣）：兩個母音中間只有「一個子音的聲音」就整組搬到後面
 * （sti．ckers、gu．mmies、ma．gic）；有兩個以上子音的聲音，照 Cambridge 的切點（bas．ket．ball、in．stant）。
 * ck、cc、dge 的第一個字母不發音（淺灰，使用者 2026-10-02：sticker 的 c 淺灰）；雙寫的子音第二個淺灰（跟 little 一樣）。
 * TV、TCG 是一個字母一個字母唸的縮寫：不放進這裡（畫面上不標母音顏色、音標）。 */
const RAW = {
 i:            'i|aɪ|aɪ',
 like:         'l|l|l i|aɪ|aɪ k|k|k e|-|-',
 to:           't|t|t o|ə|ə',
 the:          'th|ð|ð e|ə|ə',
 an:           'a|ə|ə n|n|n',
 in:           'i|ɪ|ɪ n|n|n',
 with:         'w|w|w i|ɪ|ɪ th|ð|ð',
 play:         'p|p|p l|l|l ay|eɪ|e',
 do:           'd|d|d o|uː|u',
 go:           'g|ɡ|ɡ o|oʊ|o',
 /* ── 物品1 ── */
 potato:       'p|p|p o|ə|ə / t|t|t a|eɪ|e / t|t|t o|oʊ|o',
 chips:        'ch|tʃ|tʃ i|ɪ|ɪ p|p|p s|s|s',
 instant:      'i|ɪ|ɪ n|n|n / s|s|s t|t|t a|ə|ə n|n|n t|t|t',
 noodles:      'n|n|n oo|uː|u / d|d|d l|əl|əl e|-|- s|z|z',
 chocolate:    'ch|tʃ|tʃ o|ɑː|ɑ c|k|k o|-|- / l|l|l a|ə|ə t|t|t e|-|-',
 cookies:      'c|k|k oo|ʊ|ʊ / k|k|k ie|i|ɪ s|z|z',
 candy:        'c|k|k a|æ|æ n|n|n / d|d|d y|i|ɪ',
 gummies:      'g|ɡ|ɡ u|ʌ|ʌ / m|m|m m|-|- ie|i|ɪ s|z|z',
 donuts:       'd|d|d o|oʊ|o / n|n|n u|ʌ|ʌ t|t|t s|s|s',
 ice:          'i|aɪ|aɪ c|s|s e|-|-',
 cream:        'c|k|k r|r|r ea|iː|i m|m|m',
 bubble:       'b|b|b u|ʌ|ʌ / b|b|b b|-|- l|əl|əl e|-|-',
 tea:          't|t|t ea|iː|i',
 cola:         'c|k|k o|oʊ|o / l|l|l a|ə|ə',
 juice:        'j|dʒ|dʒ ui|uː|u c|s|s e|-|-',
 french:       'f|f|f r|r|r e|e|ɛ n|n|n ch|tʃ|tʃ',
 fries:        'f|f|f r|r|r ie|aɪ|aɪ s|z|z',
 fried:        'f|f|f r|r|r ie|aɪ|aɪ d|d|d',
 chicken:      'ch|tʃ|tʃ i|ɪ|ɪ / c|-|- k|k|k e|ɪ|ɪ n|n|n',
 hamburgers:   'h|h|h a|æ|æ m|m|m / b|b|b ur|ɝː|ɝ / g|ɡ|ɡ er|ɚ|ɚ s|z|z',
 hot:          'h|h|h o|ɑː|ɑ t|t|t',
 dogs:         'd|d|d o|ɑː|ɔ g|ɡ|ɡ s|z|z',
 spaghetti:    's|s|s p|p|p a|ə|ə / g|ɡ|ɡ h|-|- e|e|ɛ / t|t|t t|-|- i|i|ɪ',
 sushi:        's|s|s u|uː|u / sh|ʃ|ʃ i|i|ɪ',
 ramen:        'r|r|r a|ɑː|ɑ / m|m|m e|e|ɛ n|n|n',
 curry:        'c|k|k ur|ɝː|ɝ / r|-|- y|i|ɪ',
 pizza:        'p|p|p i|iː|i z|t|t / z|s|s a|ə|ə',
 strawberries: 's|s|s t|t|t r|r|r aw|ɑː|ɔ / b|b|b e|e|ɛ / r|r|r r|-|- ie|i|ɪ s|z|z',
 milk:         'm|m|m i|ɪ|ɪ l|l|l k|k|k',
 stuffed:      's|s|s t|t|t u|ʌ|ʌ f|f|f f|-|- e|-|- d|t|t',
 animals:      'a|æ|æ / n|n|n i|ɪ|ɪ / m|m|m a|ə|ə l|l|l s|z|z',
 beyblades:    'b|b|b ey|eɪ|e / b|b|b l|l|l a|eɪ|e d|d|d e|-|- s|z|z',
 stick:        's|s|s t|t|t i|ɪ|ɪ c|-|- k|k|k',
 stickers:     's|s|s t|t|t i|ɪ|ɪ / c|-|- k|k|k er|ɚ|ɚ s|z|z',
 dolls:        'd|d|d o|ɑː|ɑ l|l|l l|-|- s|z|z',
 /* ── 物品2 ── */
 smartphones:  's|s|s m|m|m ar|ɑːr|ɑr t|t|t / ph|f|f o|oʊ|o n|n|n e|-|- s|z|z',
 smart:        's|s|s m|m|m ar|ɑːr|ɑr t|t|t',
 phone:        'ph|f|f o|oʊ|o n|n|n e|-|-',
 tablets:      't|t|t a|æ|æ b|b|b / l|l|l e|ə|ə t|t|t s|s|s',
 youtube:      'y|j|j ou|uː|u / t|t|t u|uː|u b|b|b e|-|-',
 videos:       'v|v|v i|ɪ|ɪ / d|d|d e|i|ɪ / o|oʊ|o s|z|z',
 video:        'v|v|v i|ɪ|ɪ / d|d|d e|i|ɪ / o|oʊ|o',
 games:        'g|ɡ|ɡ a|eɪ|e m|m|m e|-|- s|z|z',
 television:   't|t|t e|e|ɛ / l|l|l e|ə|ə / v|v|v i|ɪ|ɪ / s|ʒ|ʒ i|-|- o|ə|ə n|n|n',
 minecraft:    'm|m|m i|aɪ|aɪ n|n|n e|-|- / c|k|k r|r|r a|æ|æ f|f|f t|t|t',
 roblox:       'r|r|r o|oʊ|o / b|b|b l|l|l o|ɑː|ɑ x|ks|ks',
 'pokémon':    'p|p|p o|oʊ|o / k|k|k é|iː|i / m|m|m o|ɑː|ɑ n|n|n',
 pocket:       'p|p|p o|ɑː|ɑ / c|-|- k|k|k e|ɪ|ɪ t|t|t',
 splatoon:     's|s|s p|p|p l|l|l a|æ|æ / t|t|t oo|uː|u n|n|n',
 mario:        'm|m|m a|ɑː|ɑ / r|r|r i|i|ɪ / o|oʊ|o',
 kart:         'k|k|k ar|ɑːr|ɑr t|t|t',
 animal:       'a|æ|æ / n|n|n i|ɪ|ɪ / m|m|m a|ə|ə l|l|l',
 crossing:     'c|k|k r|r|r o|ɑː|ɔ / s|s|s s|-|- i|ɪ|ɪ ng|ŋ|ŋ',
 switch:       's|s|s w|w|w i|ɪ|ɪ tch|tʃ|tʃ',
 basket:       'b|b|b a|æ|æ s|s|s / k|k|k e|ə|ə t|t|t',
 ball:         'b|b|b a|ɑː|ɔ ll|l|l',
 basketball:   'b|b|b a|æ|æ s|s|s / k|k|k e|ə|ə t|t|t / b|b|b a|ɑː|ɔ ll|l|l',
 badminton:    'b|b|b a|æ|æ d|d|d / m|m|m i|ɪ|ɪ n|n|n / t|t|t o|ə|ə n|n|n',
 soccer:       's|s|s o|ɑː|ɑ / c|-|- c|k|k er|ɚ|ɚ',
 base:         'b|b|b a|eɪ|e s|s|s e|-|-',
 baseball:     'b|b|b a|eɪ|e s|s|s e|-|- / b|b|b a|ɑː|ɔ ll|l|l',
 comics:       'c|k|k o|ɑː|ɑ / m|m|m i|ɪ|ɪ c|k|k s|s|s',
 picture:      'p|p|p i|ɪ|ɪ c|k|k / t|tʃ|tʃ ur|ɚ|ɚ e|-|-',
 books:        'b|b|b oo|ʊ|ʊ k|k|k s|s|s',
 detective:    'd|d|d e|ɪ|ɪ / t|t|t e|e|ɛ c|k|k / t|t|t i|ɪ|ɪ v|v|v e|-|-',
 stories:      's|s|s t|t|t o|ɔː|ɔ / r|r|r ie|i|ɪ s|z|z',
 science:      's|s|s c|-|- i|aɪ|aɪ / e|ə|ə n|n|n c|s|s e|-|-',
 music:        'm|m|m u|juː|ju / s|z|z i|ɪ|ɪ c|k|k',
 cats:         'c|k|k a|æ|æ t|t|t s|s|s',
 dog:          'd|d|d o|ɑː|ɔ g|ɡ|ɡ',
 /* ── 活動1 ── */
 run:          'r|r|r u|ʌ|ʌ n|n|n',
 swim:         's|s|s w|w|w i|ɪ|ɪ m|m|m',
 ride:         'r|r|r i|aɪ|aɪ d|d|d e|-|-',
 bike:         'b|b|b i|aɪ|aɪ k|k|k e|-|-',
 bicycle:      'b|b|b i|aɪ|aɪ / c|s|s y|ɪ|ɪ / c|k|k l|əl|əl e|-|-',
 camping:      'c|k|k a|æ|æ m|m|m / p|p|p i|ɪ|ɪ ng|ŋ|ŋ',
 piano:        'p|p|p i|i|ɪ / a|æ|æ / n|n|n o|oʊ|o',
 drums:        'd|d|d r|r|r u|ʌ|ʌ m|m|m s|z|z',
 taekwondo:    't|t|t ae|aɪ|aɪ / k|k|k w|w|w o|ɑː|ɑ n|n|n / d|d|d o|oʊ|o',
 dance:        'd|d|d a|æ|æ n|n|n c|s|s e|-|-',
 sing:         's|s|s i|ɪ|ɪ ng|ŋ|ŋ',
 draw:         'd|d|d r|r|r aw|ɑː|ɔ',
 speak:        's|s|s p|p|p ea|iː|i k|k|k',
 english:      'e|ɪ|ɪ n|ŋ|ŋ / g|ɡ|ɡ l|l|l i|ɪ|ɪ sh|ʃ|ʃ',
 crafts:       'c|k|k r|r|r a|æ|æ f|f|f t|t|t s|s|s',
 park:         'p|p|p ar|ɑːr|ɑr k|k|k',
 outside:      'ou|aʊ|aʊ t|t|t / s|s|s i|aɪ|aɪ d|d|d e|-|-',
 out:          'ou|aʊ|aʊ t|t|t',
 side:         's|s|s i|aɪ|aɪ d|d|d e|-|-',
 tag:          't|t|t a|æ|æ g|ɡ|ɡ',
 guitar:       'g|ɡ|ɡ u|-|- i|ɪ|ɪ / t|t|t ar|ɑːr|ɑr',
 magic:        'm|m|m a|æ|æ / g|dʒ|dʒ i|ɪ|ɪ c|k|k',
 tricks:       't|t|t r|r|r i|ɪ|ɪ c|-|- k|k|k s|s|s',
 dodge:        'd|d|d o|ɑː|ɑ d|-|- g|dʒ|dʒ e|-|-',
 dodgeball:    'd|d|d o|ɑː|ɑ d|-|- g|dʒ|dʒ e|-|- / b|b|b a|ɑː|ɔ ll|l|l',
 /* ── 活動2 ── */
 mobile:       'm|m|m o|oʊ|o / b|b|b i|ə|ə l|l|l e|-|-',
 watch:        'w|w|w a|ɑː|ɑ tch|tʃ|tʃ',
 collect:      'c|k|k o|ə|ə / l|l|l l|-|- e|e|ɛ c|k|k t|t|t',
 cards:        'c|k|k ar|ɑːr|ɑr d|d|d s|z|z',
 beyblade:     'b|b|b ey|eɪ|e / b|b|b l|l|l a|eɪ|e d|d|d e|-|-',
 listen:       'l|l|l i|ɪ|ɪ / s|s|s t|-|- e|ə|ə n|n|n',
 read:         'r|r|r ea|iː|i d|d|d',
 chat:         'ch|tʃ|tʃ a|æ|æ t|t|t',
 friends:      'f|f|f r|r|r i|-|- e|e|ɛ n|n|n d|d|d s|z|z',
 eat:          'ea|iː|i t|t|t',
 snacks:       's|s|s n|n|n a|æ|æ c|-|- k|k|k s|s|s',
 toys:         't|t|t oy|ɔɪ|ɔɪ s|z|z',
 cook:         'c|k|k oo|ʊ|ʊ k|k|k',
 stay:         's|s|s t|t|t ay|eɪ|e',
 home:         'h|h|h o|oʊ|o m|m|m e|-|-',
 make:         'm|m|m a|eɪ|e k|k|k e|-|-',
 amusement:    'a|ə|ə / m|m|m u|juː|ju s|z|z e|-|- / m|m|m e|ə|ə n|n|n t|t|t',
 amuse:        'a|ə|ə / m|m|m u|juː|ju s|z|z e|-|-',
 visit:        'v|v|v i|ɪ|ɪ / s|z|z i|ɪ|ɪ t|t|t',
 grandparents: 'g|ɡ|ɡ r|r|r a|æ|æ n|n|n d|d|d / p|p|p a|e|ɛ / r|r|r e|ə|ə n|n|n t|t|t s|s|s',
 shopping:     'sh|ʃ|ʃ o|ɑː|ɑ / p|p|p p|-|- i|ɪ|ɪ ng|ŋ|ŋ',
 bake:         'b|b|b a|eɪ|e k|k|k e|-|-',
 cakes:        'c|k|k a|eɪ|e k|k|k e|-|- s|s|s',
 write:        'w|-|- r|r|r i|aɪ|aɪ t|t|t e|-|-',
 code:         'c|k|k o|oʊ|o d|d|d e|-|-',
 lego:         'l|l|l e|e|ɛ / g|ɡ|ɡ o|oʊ|o',
 straw:        's|s|s t|t|t r|r|r aw|ɑː|ɔ',
 berry:        'b|b|b e|e|ɛ / r|r|r r|-|- y|i|ɪ'
};
/* 一個字母一個字母唸的縮寫：照原樣畫、點了一樣會唸，不標母音顏色、音標、音節 */
const PLAIN = ['TV', 'TCG'];

/* ── 出處（人氣證據）：名稱＋日期＋對象，跟查證檔「出處核對總表」一致 ── */
const SRC = {
 G25: '學研教育總研《小学生白書》2025 年 11 月調查（日本小學生 1,200 人本人作答，官方網站）',
 G24: '學研教育總研《小学生白書》2024 年 11 月調查（日本小學生 1,200 人，官方網站）',
 J1:  '學研《小学生白書》2025 調查；Yahoo! ニュース 2026-03-16 報導（日本小學生）',
 J2:  '學研 2024-11 才藝課調查（日本小學生 1,200 人）；ねとらぼ報導',
 J3:  'ニコ☆プチ「小學生好きなものランキング 2025 食物篇」（2025-12-24，日本小學生讀者）',
 J4:  '小學館 2025 小學生年度趨勢調查（小學生讀者，2025-11-26）',
 K1:  'JTBC 2024-03-06 報導：emart24 × 零用錢 App 調查（韓國小學生 7,165 人）',
 HK:  '小學館 HugKum《小学一年生》2024 年 11 月號讀者調查（日本一年級 500 人，2024-12-30）',
 S3:  '兒福聯盟 學童飲食調查記者會（2026-01-04）',
 S4:  'TVBS 2026-05-22 報導：全國餐盒公會 學生營養午餐調查',
 S7:  '教育部 112 年（2023）調查；中央社 2024-09-02 報導（國小 4～6 年級等 4,937 人）',
 S8:  '巴哈姆特 2025-12-11：App Store 台灣 2025 排行',
 S9:  'Google Play 台灣 2025 年度最佳',
 S10: '金車教育基金會 國中小學生運動調查；聯合報 2026-05-27 報導',
 S17: '親子天下 樂讀少年調查；Openbook 閱讀誌 2025-06-16',
 S20: 'TVBS 2024-05-17 報導：兒童才藝網路聲量（2023-04～2024-04，家長的討論）',
 U3:  'Kidscreen 2025-10-17：Childwise 2025 夏季調查（英國 7～12 歲）',
 U5:  'Youth Sports Business Report 2025-08-05（Harris Poll 2025-03，美國 8～12 歲 500 多人）',
 OIA: 'Outdoor Foundation《2025 Outdoor Participation Trends Report》（美國 6～17 歲，2024 年資料）',
 NS:  'ニフティキッズ「シール」調查（日本小中學生 2,484 人，2025-12-23～2026-01-26）；共同通信 OVO 2026-03-02',
 NF:  'ニフティキッズ 寵物調查（日本小中學生 2,220 人，2024-11-14）',
 NM:  'ニフティキッズ 影音／音樂調查（日本小中學生，2024-04-11）',
 SG:  '小學館《コロコロコミック》讀者調查（2025-04～05；2025-08-07 發表）',
 NPO: '放課後 NPO アフタースクール《小學生長假怎麼過 2025》（雙薪家庭小學生 1,200 人，2025-06-26）',
 CZ:  'CITIZEN「親子相處時間」調查 2025（小學生家長 400 組，2025-06-10）',
 PT:  'ねとらぼ「小學生女生將來想做的職業」2025（女生 900 人，2026-02-21）',
 WK:  '維基百科「Mario Kart World」（2026-09-11 版）',
 YH:  '親子天下〈為什麼小學體育課要上躲避球〉Yahoo 轉載（2019-12-17）',
 NG:  'Google Books Ngram（2018～2022 英文書）；LEGO 官方 Fair Play 寫法規定',
 BD:  '萬代 2025 聖誕禮物調查（3～12 歲孩子的家長 600 人，2025-11-27）'
};
const S = (...k) => k.map(x => SRC[x]).join('；');
const E = (t, flag, who, bars, s, d, kids, kw) => ({ t, flag, who, bars, s, d, kids, kw });
const JP = '日本小學生', KR = '韓國小學生', TW = '台灣小學生';

/* ── 出處第 2 條：字源／結構（每一條都打開原始頁面核對過；年份換算成「大約 N 年前」以 2026 年計） ── */
const EM = w => 'Etymonline「' + w + '」';
const ET = {
 potato: { t: '🥔 potato 從哪裡來？', ch: 1, eq: [['🏝️', 'batata', '海地的話：甘藷'], [WF('es'), 'patata', '西班牙文'], ['🥔', 'potato', '馬鈴薯']], s: EM('potato (n.)'),
  d: '海地當地的話 <b>batata</b>（甘藷）➜ 西班牙文 <b>patata</b> ➜ 英文 <b>potato</b>，1560 年代（大約 460 年前）。' },
 noodle: { t: '🍜 noodle 從德國來', ch: 1, eq: [[WF('de'), 'Nudel', '德文'], ['🍜', 'noodle', '麵']], s: EM('noodle (n.1)'),
  d: '德文 <b>Nudel</b> ➜ 英文 <b>noodle</b>，1779 年（大約 250 年前）。' },
 chocolate: { t: '🍫 chocolate 從墨西哥來', ch: 1, eq: [['🌎', 'chocolatl', '阿茲特克人的話'], [WF('es'), 'chocolate', '西班牙文'], ['🍫', 'chocolate', '巧克力']], s: EM('chocolate (n.)'),
  d: '墨西哥的阿茲特克人說 <b>chocolatl</b>，一開始是<b>泡水喝的飲料</b>；大約 1600 年進到英文（大約 430 年前）。' },
 cookie: { t: '🍪 cookie ＝ 荷蘭的「小蛋糕」', ch: 1, eq: [[WF('nl'), 'koekje', '荷蘭文：小蛋糕'], ['🍪', 'cookie', '餅乾']], s: EM('cookie (n.)'),
  d: '荷蘭文 <b>koekje</b> ＝ <b>小蛋糕</b>。「小小甜甜的餅」這個意思，1808 年在美國開始用（大約 220 年前）。' },
 candy: { t: '🍬 candy 從波斯來', ch: 1, eq: [['🌾', 'qand', '波斯文：甘蔗糖'], [WF('fr'), 'sucre candi', '法文：冰糖'], ['🍬', 'candy', '糖果']], s: EM('candy (n.)'),
  d: '波斯文 <b>qand</b>（甘蔗糖）➜ 阿拉伯文 ➜ 法文 <b>çucre candi</b> ➜ 英文 <b>candy</b>，1200 年代後期（大約 750 年前）。' },
 gummy: { t: '🧩 gummy ＝ gum ＋ y', eq: [['🧴', 'gum', '膠'], ['✨', 'y', '像……的'], [I.gummy, 'gummy', '像膠一樣黏黏的']], s: EM('gummy (adj.)'),
  d: '<b>gum</b>（膠）＋ <b>-y</b> ＝ <b>gummy 黏黏的、像膠一樣</b>。1300 年代後期就有（大約 650 年前）。' },
 donut: { t: '🧩 donut ＝ dough ＋ nut', eq: [['🍞', 'dough', '麵團'], ['🌰', 'nut', '堅果'], ['🍩', 'doughnut', '甜甜圈']], s: EM('doughnut (n.)') + '；' + EM('donut (n.)'),
  d: '一開始是<b>一小球</b>炸麵團，像一顆堅果（中間的洞後來才有）。1809 年（大約 220 年前）；美國 1870 年起也寫成 <b>donut</b>。' },
 icecream: { t: '🧩 ice cream ＝ ice ＋ cream', eq: [['🧊', 'ice', '冰'], ['🥛', 'cream', '奶油'], ['🍦', 'ice cream', '冰淇淋']], s: EM('ice-cream (n.)'),
  d: '1680 年代叫 <b>iced cream</b>（冰過的奶油），1744 年變成 <b>ice cream</b>（大約 280 年前）。' },
 tea: { t: '🍵 tea 和台語的「茶」是一家人', ch: 1, eq: [['🏯', 'te', '廈門話：茶'], [WF('nl'), 'thee', '荷蘭文'], ['🍵', 'tea', '茶']], s: EM('tea (n.)') + '；教育部臺灣台語常用詞辭典「茶」',
  d: '中國<b>廈門話</b>的「茶」➜ 荷蘭文 <b>thee</b> ➜ 英文 <b>tea</b>（1650 年代）。台語的「茶」唸 <b>tê</b>，跟 tea 很像！' },
 cola: { t: '🥤 cola 本來是一種樹', ch: 1, eq: [['🌳', 'kola', '西非的樹'], ['🥤', 'cola', '可樂']], s: EM('cola (n.)'),
  d: 'cola 本來是<b>西非一種樹</b>的名字，種子裡有咖啡因。1919 年起當「<b>汽水</b>」用（Coca-Cola、Pepsi-Cola 的簡稱，大約 110 年前）。' },
 juice: { t: '🧃 juice 從法國來', ch: 1, eq: [['🍲', 'ius', '拉丁文：湯汁'], [WF('fr'), 'jus', '法文：汁'], ['🧃', 'juice', '果汁']], s: EM('juice (n.)'),
  d: '拉丁文 <b>ius</b>（湯、醬汁）➜ 法文 <b>jus</b> ➜ 英文 <b>juice</b>，大約 1300 年（大約 730 年前）。' },
 fry: { t: '🍟 fry ＝ 炸', ch: 1, eq: [[WF('fr'), 'frire', '法文：炸'], ['🍳', 'fry', '炸'], ['🍟', 'French fries', '薯條']], s: EM('fry (v.)') + '；Merriam-Webster「french fry」',
  d: '<b>fry</b>（炸）來自法文 <b>frire</b>。<b>French fries</b> 這個說法最早在 1886 年（大約 140 年前）。' },
 chicken: { t: '🐣 chicken 可能是學小雞叫', ch: 1, eq: [['🐣', 'cicen', '古英文：小雞'], ['🍗', 'chicken', '雞']], s: EM('chicken (n.)'),
  d: '古英文就有 <b>cicen</b>（小雞）：可能是模仿<b>小雞的叫聲</b>變來的。' },
 hamburger: { t: '🍔 hamburger 和德國的漢堡市', ch: 1, eq: [[WF('de'), 'Hamburger', '漢堡市的人'], ['🥩', 'hamburg steak', '漢堡肉排'], ['🍔', 'hamburger', '漢堡']], s: EM('hamburger (n.)'),
  d: '<b>Hamburger</b> 本來是「<b>德國漢堡市的人</b>」；1880 年有 hamburg steak（漢堡肉排）。<b>為什麼用這個城市的名字，沒有確定的說法。</b>' },
 spaghetti: { t: '🍝 spaghetti ＝ 很多條小細繩', ch: 1, eq: [[WF('it'), 'spago', '繩子'], [WF('it'), 'spaghetto', '小細繩'], ['🍝', 'spaghetti', '很多條小細繩']], s: EM('spaghetti (n.)'),
  d: '義大利文 <b>spago</b>（繩子）➜ <b>spaghetto</b>（小細繩）➜ 很多條就是 <b>spaghetti</b>。1845 年（大約 180 年前）。' },
 sushi: { t: '🍣 sushi 從日本來', ch: 1, eq: [['🍚', 'すし', '日文'], ['🍣', 'sushi', '壽司']], s: EM('sushi (n.)'),
  d: '日文「すし」1875 年進到英文（大約 150 年前）。據說本來指的是<b>醋飯</b>，不是上面的魚。' },
 ramen: { t: '🍜 ramen ＝ 中文的「拉麵」', ch: 1, eq: [['🥢', '拉麵', '中文：拉出來的麵'], ['🗾', 'ラーメン', '日文'], ['🍜', 'ramen', '拉麵']], s: EM('ramen (n.)'),
  d: '中文「<b>拉麵</b>」➜ 日文 ➜ 英文 <b>ramen</b>，1962 年（大約 60 年前）。' },
 curry: { t: '🍛 curry 從印度南部來', ch: 1, eq: [['🌶️', 'kari', '印度南部的話'], ['⛵', 'caril', '葡萄牙文'], ['🍛', 'curry', '咖哩']], s: EM('curry (n.)'),
  d: '印度南部的話 <b>kari</b> ➜ 葡萄牙文 ➜ 英文 <b>curry</b>，1590 年代（大約 430 年前）。' },
 pizza: { t: '🍕 pizza 從義大利來', ch: 1, eq: [[WF('it'), 'pizza', '義大利文：餅、派'], ['🍕', 'pizza', '披薩']], s: EM('pizza (n.)'),
  d: '義大利文 <b>pizza</b> 本來是「<b>餅、派</b>」，1845 年進到英文（大約 180 年前）。名字從哪裡來，<b>沒有確定的說法</b>。' },
 strawberry: { t: '🧩 strawberry ＝ straw ＋ berry', eq: [['🌾', 'straw', '稻草'], ['🍇', 'berry', '莓果'], ['🍓', 'strawberry', '草莓']], s: EM('strawberry (n.)'),
  d: '古英文就叫 <b>streawberige</b>。<b>為什麼有「稻草」，沒有確定的說法</b>（可能是表面一粒一粒像碎稻草的籽）。' },
 milk: { t: '🥛 milk：一千多年前就這樣叫', ch: 1, eq: [['🐄', 'meoluc', '古英文'], ['🥛', 'milk', '牛奶']], s: EM('milk (n.)'),
  d: '古英文 <b>meoluc</b>；德文 <b>Milch</b>、荷蘭文 <b>melk</b> 都是一家人。可能來自「<b>用手擠</b>」的動作。' },
 stuffed: { t: '🧩 stuffed ＝ stuff ＋ ed', eq: [['🧵', 'stuff', '塞東西'], ['✅', 'ed', '被……的'], ['🧸', 'stuffed', '塞滿的']], s: EM('stuffed (adj.)'),
  d: '<b>stuffed</b> ＝ <b>塞滿東西的</b>（1400 年代中期就有）。stuffed animals ＝ <b>肚子塞滿東西的動物</b>。' },
 sticker: { t: '🧩 sticker ＝ stick ＋ er', eq: [['🩹', 'stick', '黏住'], ['👤', 'er', '會做這件事的'], [I.stickers, 'sticker', '會黏住的東西 ＝ 貼紙']], s: EM('sticker (n.)'),
  d: '<b>stick</b>（黏住）＋ <b>-er</b> ＝ <b>會黏住的東西</b>。「貼紙」這個意思從 <b>1871 年</b>開始用（<b>大約 150 年前</b>）。' },
 doll: { t: '👧 doll 本來是女生的名字', ch: 1, eq: [['👧', 'Dorothy', '女生的名字'], ['💬', 'Doll', '小名'], [I.doll, 'doll', '娃娃']], s: EM('doll (n.)'),
  d: '<b>Doll</b> 本來是 <b>Dorothy</b> 的小名；1700 年開始指<b>小孩玩的娃娃</b>（大約 330 年前）。' },
 smartphone: { t: '🧩 smartphone ＝ smart ＋ phone', eq: [['🧠', 'smart', '聰明的'], ['📞', 'phone', '電話'], ['📱', 'smartphone', '智慧型手機']], s: 'Merriam-Webster「smartphone」；' + EM('phone (n.1)'),
  d: '<b>phone</b> 是 telephone 的簡稱（1878 年）。<b>smartphone</b> 最早在 1996 年（大約 30 年前）。' },
 tablet: { t: '📟 tablet ＝ 一塊小板子', ch: 1, eq: [[WF('fr'), 'tablete', '法文：小板子'], [I.tablet, 'tablet', '平板']], s: EM('tablet (n.)'),
  d: '法文 <b>tablete</b> ＝ <b>小桌子、小板子</b>；大約 1300 年就有，以前是<b>一塊可以寫字的小板子</b>。' },
 tv: { t: '🧩 TV ＝ television', eq: [['🔭', 'tele', '遠'], ['👀', 'vision', '看見'], ['📺', 'television', '電視']], s: EM('television (n.)') + '；' + EM('tele-'),
  d: '<b>tele</b>（遠）＋ <b>vision</b>（看見）＝ <b>看見很遠的地方</b>。1907 年就有這個字；簡稱 <b>TV</b> 是 1948 年（大約 80 年前）。' },
 video: { t: '👁️ video ＝ 拉丁文「我看見」', ch: 1, eq: [['👁️', 'video', '拉丁文：我看見'], ['🎬', 'video', '影片']], s: EM('video (adj., n.)'),
  d: '拉丁文 <b>video</b> ＝「<b>我看見</b>」。1935 年進到英文；<b>video game</b> 1972 年（大約 50 年前）。' },
 game: { t: '🎮 game 本來是「好玩」', ch: 1, eq: [['😄', 'gamen', '古英文：快樂、好玩'], ['🎮', 'game', '遊戲']], s: EM('game (n.)'),
  d: '古英文 <b>gamen</b> ＝ <b>快樂、好玩</b>；「照規則比賽」這個意思大約 1200 年就有。' },
 pokemon: { t: '🧩 Pokémon ＝ Pocket Monsters', eq: [['👖', 'Pocket', '口袋'], ['👾', 'Monsters', '怪獸'], [I.card, 'Pokémon', '寶可夢']], s: '維基百科「Pokémon」',
  d: '日本的名字本來是 <b>Pocket Monsters</b>（口袋怪獸），剪短變成 <b>Pokémon</b>。' },
 kart: { t: '🏎️ kart ＝ go-kart', ch: 1, eq: [[I.kart, 'go-kart', '卡丁車'], ['✂️', 'kart', '剪短']], s: EM('kart (n.)'),
  d: '<b>kart</b> 是 <b>go-kart</b>（卡丁車）的簡稱，1957 年，美國（大約 70 年前）。' },
 animal: { t: '🐾 animal ＝ 會呼吸的', ch: 1, eq: [['🌬️', 'anima', '拉丁文：呼吸'], ['🐾', 'animal', '動物']], s: EM('animal (n.)'),
  d: '拉丁文 <b>anima</b> ＝ <b>呼吸</b>；animal ＝ <b>會呼吸的生物</b>（1300 年代初期）。' },
 basketball: { t: '🧩 basketball ＝ basket ＋ ball', eq: [['🧺', 'basket', '籃子'], ['⚽', 'ball', '球'], ['🏀', 'basketball', '籃球']], s: EM('basketball (n.)'),
  d: '<b>basket</b>（籃子）＋ <b>ball</b>（球）。<b>1891 年</b>，在美國教體育的 <b>James Naismith</b> 發明這個運動，<b>1892 年</b>開始叫 basketball（<b>大約 130 年前</b>）。' },
 badminton: { t: '🏸 badminton 是一座莊園的名字', ch: 1, eq: [['🌏', 'poona', '印度的遊戲'], ['🏰', 'Badminton', '英國的莊園'], [I.shuttle, 'badminton', '羽毛球']], s: EM('badminton (n.)'),
  d: '英國軍官在<b>印度</b>學到這個遊戲，在一位公爵的莊園 <b>Badminton House</b> 玩起來，1874 年就用莊園的名字（大約 150 年前）。' },
 soccer: { t: '✂️ soccer 是剪出來的字', ch: 1, eq: [['⚽', 'Association', '協會（足球）'], ['✂️', 'Assoc.', '剪短'], ['⚽', 'soccer', '足球']], s: EM('soccer (n.)'),
  d: '英國大學生的流行語：<b>Association football</b>（協會足球）剪成 <b>Assoc.</b>，再變成 <b>soccer</b>（1889 年，大約 140 年前）。' },
 baseball: { t: '🧩 baseball ＝ base ＋ ball', eq: [['📍', 'base', '壘（安全的地方）'], ['⚾', 'ball', '球'], ['⚾', 'baseball', '棒球']], s: EM('baseball (n.)'),
  d: '<b>base</b>（壘：跑到就安全的地方）＋ <b>ball</b>。1845 年，美國（大約 180 年前）。' },
 comic: { t: '😂 comic ＝ 好笑的', ch: 1, eq: [['🎭', 'komikos', '希臘文：喜劇的'], [I.comic, 'comics', '漫畫']], s: EM('comic (n.)'),
  d: '希臘文 <b>komikos</b>（喜劇的、好笑的）；1890 年起 <b>comics</b> 指<b>好笑的圖畫</b>（大約 135 年前）。' },
 picture: { t: '🖼️ picture ＝ 畫', ch: 1, eq: [['🎨', 'pictura', '拉丁文：畫'], ['📖', 'picture book', '圖畫書']], s: EM('picture (n.)'),
  d: '拉丁文 <b>pictura</b> ＝ <b>畫</b>；<b>picture-book</b>（給小孩的圖畫書）1801 年就有（大約 225 年前）。' },
 detective: { t: '🧩 detective ＝ detect ＋ ive', eq: [['🔍', 'detect', '查出來'], ['💪', 'ive', '很會……的'], ['🕵️', 'detective', '偵探']], s: EM('detective (n.)'),
  d: '<b>detect</b>（查出來）＋ <b>-ive</b>：<b>很會查出來的人</b>。1828 年（大約 200 年前）。' },
 science: { t: '🔬 science ＝ 知道', ch: 1, eq: [['💡', 'scire', '拉丁文：知道'], ['🔬', 'science', '科學']], s: EM('science (n.)'),
  d: '拉丁文 <b>scire</b> ＝ <b>知道</b>；science 本來的意思就是「<b>知識</b>」。' },
 book: { t: '📚 book 可能跟樹有關', ch: 1, eq: [['🌳', 'beech', '山毛櫸'], ['🪵', 'boc', '古英文：書'], ['📚', 'book', '書']], s: EM('book (n.)'),
  d: '古英文 <b>boc</b>；可能跟<b>山毛櫸樹</b>有關：以前把字刻在木板上。德文 <b>Buch</b>（書）、<b>Buche</b>（山毛櫸）。' },
 music: { t: '🎵 music ＝ 繆思女神的藝術', ch: 1, eq: [['🏛️', 'mousikē', '希臘文'], ['🎵', 'music', '音樂']], s: EM('music (n.)'),
  d: '希臘文 <b>mousikē</b> ＝「<b>繆思女神的藝術</b>」；英文 1200 年代中期就有（大約 780 年前）。' },
 dog: { t: '🐶 dog 是英文最大的謎之一', ch: 1, eq: [['🐕', 'hund', '以前的說法'], ['🐶', 'dog', '狗']], s: EM('dog (n.)'),
  d: '古英文 <b>docga</b>，從哪裡來是<b>英文字源最大的謎之一</b>！以前英文說 <b>hund</b>（德文今天還說 Hund）。' },
 cat: { t: '🐱 cat 從拉丁文來', ch: 1, eq: [['🏛️', 'cattus', '拉丁文'], ['🐱', 'cat', '貓']], s: EM('cat (n.)'),
  d: '拉丁文 <b>cattus</b>；荷蘭文 <b>kat</b>、德文 <b>Katze</b> 都是一家人。古英文大約 700 年就有 catt（大約 1300 年前）。' },
 run: { t: '🏃 run：一千多年前就有', ch: 1, eq: [['🏃', 'rinnan', '古英文：跑、流'], ['🏃', 'run', '跑']], s: EM('run (v.)'),
  d: '古英文 <b>rinnan</b> ＝ <b>跑、流</b>；德文 <b>rinnen</b> ＝ 流。' },
 swim: { t: '🏊 swim：一千多年前就有', ch: 1, eq: [['🏊', 'swimman', '古英文'], ['🏊', 'swim', '游泳']], s: EM('swim (v.)'),
  d: '古英文 <b>swimman</b>；德文 <b>schwimmen</b>、荷蘭文 <b>zwemmen</b> 都是一家人。' },
 bike: { t: '🧩 bike ＝ bicycle', eq: [['2️⃣', 'bi', '兩個'], ['⭕', 'cycle', '輪子'], ['🚲', 'bicycle', '腳踏車']], s: EM('bicycle (n.)') + '；' + EM('bike (n.)'),
  d: '<b>bi</b>（兩個）＋ <b>cycle</b>（輪子）＝ <b>兩個輪子</b>，1868 年；1882 年剪短變成 <b>bike</b>（大約 140 年前）。' },
 camp: { t: '🏕️ camp ＝ 空地', ch: 1, eq: [['🌾', 'campus', '拉丁文：空地'], ['🏕️', 'camping', '露營']], s: EM('camp (n.)') + '；' + EM('camp (v.)'),
  d: '拉丁文 <b>campus</b> ＝ <b>空地、田野</b>；<b>camping out</b>（在外面露營）1834 年，美國（大約 190 年前）。' },
 piano: { t: '🎹 piano ＝ 小聲', ch: 1, eq: [['🔉', 'piano e forte', '小聲和大聲'], ['🎹', 'pianoforte', '可以彈小聲大聲的琴'], ['🎹', 'piano', '鋼琴']], s: EM('pianoforte (n.)') + '；' + EM('piano (n.)'),
  d: '義大利文 <b>piano e forte</b> ＝「<b>小聲和大聲</b>」：鋼琴可以彈得小聲、也可以彈得大聲。剪短就是 <b>piano</b>（1803 年）。' },
 drum: { t: '🥁 drum：咚咚咚', ch: 1, eq: [[WF('nl'), 'tromme', '荷蘭文'], ['🥁', 'drum', '鼓']], s: EM('drum (n.)'),
  d: '荷蘭文 <b>tromme</b>，可能是<b>模仿打鼓的聲音</b>；1400 年代初期（大約 600 年前）。' },
 taekwondo: { t: '🧩 taekwondo ＝ tae ＋ kwon ＋ do', eq: [['🦶', 'tae', '踢'], ['✊', 'kwon', '拳頭'], ['🛤️', 'do', '道']], s: 'Merriam-Webster「taekwondo」',
  d: '韓文：<b>tae</b>（踢）＋ <b>kwon</b>（拳頭）＋ <b>do</b>（道、方法）。1967 年進到英文（大約 60 年前）。' },
 dance: { t: '💃 dance 從法國來', ch: 1, eq: [[WF('fr'), 'dancier', '法文'], ['💃', 'dance', '跳舞']], s: EM('dance (v.)'),
  d: '法文 <b>dancier</b> ➜ 英文 <b>dance</b>（大約 1300 年）；德文 tanzen、西班牙文 danzar 也是從這個字來的。' },
 sing: { t: '🎤 sing：一千多年前就有', ch: 1, eq: [['🎶', 'singan', '古英文'], ['🎤', 'sing', '唱歌']], s: EM('sing (v.)'),
  d: '古英文 <b>singan</b>；德文 <b>singen</b>、荷蘭文 <b>zingen</b> 都是一家人。' },
 draw: { t: '✏️ draw ＝ 拉', ch: 1, eq: [['🪢', 'dragan', '古英文：拉、拖'], ['🎨', 'draw', '畫畫']], s: EM('draw (v.)'),
  d: '古英文 <b>dragan</b> ＝ <b>拉、拖</b>：用筆在紙上<b>「拉」出線條</b>，就是畫畫（大約 1200 年起）。' },
 english: { t: '🔤 English ＝ Angles 人的話', ch: 1, eq: [['⛵', 'Engle', 'Angles 人'], ['🔤', 'English', '英文']], s: EM('English (n.1)'),
  d: '<b>Englisc</b> ＝「<b>Angles 人的</b>」：1500 多年前（400 年代）坐船搬到英國的一群人。' },
 craft: { t: '✂️ craft 本來是「力氣」', ch: 1, eq: [['💪', 'cræft', '古英文：力氣'], ['✂️', 'craft', '手藝']], s: EM('craft (n.)'),
  d: '古英文 <b>cræft</b> ＝ <b>力氣</b>，後來變成「<b>手藝、技術</b>」；德文 <b>Kraft</b> 今天還是「力氣」。' },
 park: { t: '🏞️ park 本來是圍起來的林子', ch: 1, eq: [[WF('fr'), 'parc', '法文：圍起來的林地'], ['🏞️', 'park', '公園']], s: EM('park (n.)'),
  d: '法文 <b>parc</b> ＝ <b>圍起來的林地</b>，以前是給人打獵的地方（1200 年代中期）。' },
 outside: { t: '🧩 outside ＝ out ＋ side', eq: [['🚪', 'out', '外'], ['📏', 'side', '邊'], ['🌳', 'outside', '外面']], s: EM('outside (n.)'),
  d: '<b>out</b>（外）＋ <b>side</b>（邊），大約 1500 年（大約 525 年前）。' },
 tag: { t: '👉 tag ＝ 碰一下', ch: 1, eq: [['👉', 'tig', '蘇格蘭話：碰一下'], ['🏃', 'tag', '鬼抓人']], s: EM('tag (n.2)'),
  d: '可能來自蘇格蘭話 <b>tig</b> ＝ <b>碰一下</b>，1738 年就有（大約 290 年前）。<b>tag 不是縮寫</b>。' },
 guitar: { t: '🎸 guitar 從希臘一路傳過來', ch: 1, eq: [['🏛️', 'kithara', '希臘：七條弦的琴'], [WF('es'), 'guitarra', '西班牙文'], ['🎸', 'guitar', '吉他']], s: EM('guitar (n.)'),
  d: '希臘的 <b>kithara</b> ➜ 拉丁文 ➜ 西班牙文、法文 ➜ 1620 年代英文 <b>guitar</b>（大約 400 年前）。' },
 magic: { t: '🎩 magic 從古代波斯來', ch: 1, eq: [['📜', 'magush', '古波斯文：祭司'], ['🏛️', 'magikos', '希臘文'], ['🎩', 'magic', '魔術']], s: EM('magic (n.)'),
  d: '古代波斯的 <b>magush</b>（有學問的祭司）➜ 希臘文 <b>magikos</b> ➜ 英文 <b>magic</b>（1300 年代後期）。' },
 dodgeball: { t: '🧩 dodgeball ＝ dodge ＋ ball', eq: [['🏃', 'dodge', '閃躲'], ['⚽', 'ball', '球'], [I.dball, 'dodgeball', '躲避球']], s: 'Merriam-Webster「dodgeball」',
  d: '<b>dodge</b>（閃躲）＋ <b>ball</b>（球）：最早在 <b>1900 年</b>（大約 125 年前）。' },
 mobile: { t: '📱 mobile ＝ 可以移動的', ch: 1, eq: [['🏛️', 'mobilis', '拉丁文：可以移動的'], ['📱', 'mobile', '行動的']], s: EM('mobile (adj.)'),
  d: '拉丁文 <b>mobilis</b> ＝ <b>可以移動的</b>（movere ＝ 移動）；1400 年代後期（大約 530 年前）。' },
 watch: { t: '👀 watch 本來是「醒著」', ch: 1, eq: [['🌙', 'wæccan', '古英文：醒著、守著'], ['👀', 'watch', '看']], s: EM('watch (v.)'),
  d: '古英文 <b>wæccan</b> ＝ <b>醒著、守著</b>；「盯著看」這個意思 1400 年代中期才有。' },
 collect: { t: '🧩 collect ＝ 撿在一起', eq: [['🤝', 'com', '一起'], ['✋', 'legere', '撿'], ['📦', 'collect', '收集']], s: EM('collect (v.)'),
  d: '拉丁文 <b>colligere</b> ＝ <b>com</b>（一起）＋ <b>legere</b>（撿）＝ <b>撿在一起</b>；1400 年代初期（大約 600 年前）。' },
 listen: { t: '👂 listen 的 t 為什麼不唸？', ch: 1, eq: [['👂', 'hlysnan', '古英文'], ['👂', 'listen', '聽']], s: EM('listen (v.)'),
  d: '古英文 <b>hlysnan</b> 沒有 t；<b>t 可能是受 list（聽）影響才加進來的</b>，所以今天不唸。' },
 read: { t: '📖 read 本來是「給建議」', ch: 1, eq: [['💬', 'rædan', '古英文：給建議、解釋、讀'], ['📖', 'read', '讀']], s: EM('read (v.)'),
  d: '古英文 <b>rædan</b> ＝ <b>給建議、解釋</b>，也有「<b>讀</b>」的意思。' },
 chat: { t: '✂️ chat ＝ chatter 剪短', ch: 1, eq: [['🗣️', 'chatter', '嘰嘰喳喳講話'], ['✂️', 'chat', '聊天']], s: EM('chat (v.)'),
  d: '<b>chat</b> 是 <b>chatter</b>（嘰嘰喳喳講話）剪短的，1400 年代中期（大約 575 年前）。' },
 friend: { t: '💗 friend ＝ 愛', ch: 1, eq: [['💗', 'freond', '古英文：愛的人'], ['👫', 'friend', '朋友']], s: EM('friend (n.)'),
  d: '古英文 <b>freond</b>，來自「<b>愛</b>」；德文 <b>Freund</b>、荷蘭文 <b>vriend</b> 都是一家人。' },
 snack: { t: '🐶 snack 本來是狗咬一口', ch: 1, eq: [['🐶', 'snak', '狗咬一口'], ['🍪', 'snack', '點心']], s: EM('snack (n.)'),
  d: '大約 1400 年，<b>snak</b> ＝ 狗「<b>咬一口</b>」；「<b>吃一點點的小點心</b>」這個意思 1726 年才有（大約 300 年前）。' },
 toy: { t: '🧸 toy ＝ 小東西', ch: 1, eq: [['✨', 'toie', '小東西、好玩的事'], ['🧸', 'toy', '玩具']], s: EM('toy (n.)'),
  d: '大約 1300 年就有 <b>toie</b> ＝ <b>小東西、好玩的事</b>；從哪裡來，<b>沒有確定的說法</b>。' },
 cook: { t: '🍳 cook 從拉丁文來', ch: 1, eq: [['🏛️', 'coquus', '拉丁文：廚師'], ['🍳', 'cook', '做菜']], s: EM('cook (n.)') + '；' + EM('cook (v.)'),
  d: '拉丁文 <b>coquus</b>（廚師）、<b>coquere</b>（煮）；德文 <b>Koch</b> ＝ 廚師。' },
 home: { t: '🏠 home：一千多年前就有', ch: 1, eq: [['🏘️', 'ham', '古英文：住的地方'], ['🏠', 'home', '家']], s: EM('home (n.)'),
  d: '古英文 <b>ham</b> ＝ <b>住的地方、村子</b>。' },
 amusement: { t: '🧩 amusement ＝ amuse ＋ ment', eq: [['😄', 'amuse', '逗人開心'], ['📝', 'ment', '這件事'], ['🎡', 'amusement', '娛樂']], s: EM('amusement (n.)'),
  d: '<b>amusement park</b>（遊樂園）1897 年就有（大約 130 年前）。' },
 grandparents: { t: '🧩 grandparent ＝ grand ＋ parent', eq: [['⬆️', 'grand', '大'], ['👨‍👩', 'parent', '父母'], ['👴', 'grandparent', '祖父母']], s: EM('grandparent (n.)'),
  d: '<b>grand</b>（大）＋ <b>parent</b>（父母）：<b>爸爸媽媽的爸爸媽媽</b>。1802 年（大約 225 年前）。' },
 shopping: { t: '🛍️ shop 本來是小棚子', ch: 1, eq: [['🛖', 'shop', '小棚子、攤子'], ['🛍️', 'shopping', '去買東西']], s: EM('shop (n.)') + '；' + EM('shopping (n.)'),
  d: '<b>shop</b> 本來是「<b>小棚子、攤子</b>」；<b>shopping</b>（去店裡看、買東西）1764 年（大約 260 年前）。' },
 cake: { t: '🎂 cake 從維京人來', ch: 1, eq: [['⛵', 'kaka', '古北歐語（維京人）'], ['🎂', 'cake', '蛋糕']], s: EM('cake (n.)'),
  d: '古北歐語 <b>kaka</b> ➜ 英文 <b>cake</b>（1200 年代初期）；荷蘭文 <b>koek</b>、德文 <b>Kuchen</b>。' },
 code: { t: '💻 code 本來是樹幹', ch: 1, eq: [['🌳', 'codex', '拉丁文：樹幹、書'], ['📜', 'code', '法律、密碼'], ['💻', 'code', '程式']], s: EM('code (n.)') + '；' + EM('code (v.)'),
  d: '拉丁文 <b>codex</b>（樹幹 ➜ 木板做的書）➜ 法律 ➜ 密碼 ➜ 1947 年起指<b>電腦程式</b>（大約 80 年前）。' },
 lego: { t: '🧱 LEGO ＝ 丹麥文「好好玩」', ch: 1, eq: [['🇩🇰', 'leg godt', '丹麥文：好好玩'], [I.lego, 'LEGO', '樂高']], s: '維基百科「Lego」（引 LEGO 集團歷史）',
  d: '1934 年，公司取名 <b>LEGO</b>，來自丹麥文 <b>leg godt</b> ＝「<b>好好玩</b>」（play well）。' }
};
/* 丹麥國旗（emoji 國旗在 Windows 顯示成字母，2026-09-28 全站已換 SVG） */
ET.lego.eq[0][0] = '<svg class="flag" viewBox="0 0 37 28" aria-hidden="true"><rect width="37" height="28" fill="#C8102E"/><rect x="12" width="4" height="28" fill="#FFF"/><rect y="12" width="37" height="4" fill="#FFF"/></svg>';

/* ── 98 個字 ── */
const P = '<b>', Q = '</b>';
const WORDS = [
/* ══ 物品1（26）：零食、飲料、美食、水果→飲料、玩具 ══ */
 {f:'potato-chips', en:'potato chips', zh:'洋芋片', g:'i1', cat:'零食', ic:I.chips,
  tk:[['potato','馬鈴薯','🥔'],['chips','薄片',I.chips]], ex:'我喜歡洋芋片。',
  ev:E('📊 小學生愛吃洋芋片嗎？','jp',JP,[{rk:2,l:'零食部門：<b>ポテトチップス</b>（洋芋片）'}],S('J3'),'日本小學生的零食排行，<b>洋芋片第 2 名</b>。'), et:ET.potato},
 {f:'instant-noodles', en:'instant noodles', zh:'泡麵', g:'i1', cat:'零食', ic:I.cupnoodles,
  tk:[['instant','馬上的','⚡'],['noodles','麵',I.cupnoodles]], ex:'我喜歡泡麵。',
  ev:E('📊 小學生愛吃泡麵嗎？','kr',KR,[{p:30,l:'便利商店最想吃：<b>杯麵</b>'},{rk:1,l:'杯麵是<b>第 1 名</b>'}],S('K1'),'韓國 7,165 名小學生：<b>30%</b> 最想吃<b>杯麵</b>，第 1 名。',3,'小學生'), et:ET.noodle},
 {f:'chocolate', en:'chocolate', zh:'巧克力', g:'i1', cat:'零食', ic:'🍫',
  tk:[['chocolate','巧克力','🍫']], ex:'我喜歡巧克力。',
  ev:E('📊 小學生愛吃巧克力嗎？','kr',KR,[{p:18,l:'便利商店最想吃：<b>巧克力</b>'},{rk:3,l:'巧克力是<b>第 3 名</b>'}],S('K1'),'韓國小學生：<b>18%</b> 最想吃<b>巧克力</b>，第 3 名。'), et:ET.chocolate},
 {f:'cookies', en:'cookies', zh:'餅乾', g:'i1', cat:'零食', ic:'🍪',
  tk:[['cookies','餅乾','🍪']], ex:'我喜歡餅乾。',
  ev:E('📊 小學生愛吃餅乾嗎？','jp',JP,[{tx:'零食排行有一整個「<b>クッキー</b>」（餅乾）部門，排到第 1～5 名',ic:'🍪'}],S('J3'),'日本小學生最喜歡的零食，<b>餅乾自己就有一個部門</b>。'), et:ET.cookie},
 {f:'candy', en:'candy', zh:'糖果', g:'i1', cat:'零食', ic:'🍬',
  tk:[['candy','糖果','🍬']], ex:'我喜歡糖果。',
  ev:E('📊 小學生愛吃糖果嗎？','jp',JP,[{tx:'零食排行有一整個「<b>あめ</b>」（糖果）部門，排到第 1～5 名',ic:'🍬'}],S('J3'),'日本小學生最喜歡的零食，<b>糖果自己就有一個部門</b>。'), et:ET.candy},
 {f:'gummies', en:'gummies', zh:'軟糖', g:'i1', cat:'零食', ic:I.gummy,
  tk:[['gummies','軟糖',I.gummy]], ex:'我喜歡軟糖。',
  ev:E('📊 小學生愛吃軟糖嗎？','jp',JP,[{rk:5,l:'最喜歡的食物：<b>グミ</b>（軟糖）'}],S('J3'),'日本小學生最喜歡的食物，<b>軟糖第 5 名</b>（還另外有一個軟糖部門）。'), et:ET.gummy},
 {f:'donuts', en:'donuts', zh:'甜甜圈', g:'i1', cat:'零食', ic:'🍩',
  tk:[['donuts','甜甜圈','🍩']], ex:'我喜歡甜甜圈。',
  ev:E('📊 小學生愛吃甜甜圈嗎？','jp',JP,[{p:10.1,l:'最喜歡的食物：<b>ドーナツ</b>（甜甜圈）'},{rk:12,l:'甜甜圈是<b>第 12 名</b>'}],S('G25'),'日本 1,200 名小學生：<b>10.1%</b> 最喜歡<b>甜甜圈</b>，第 12 名。',1,'小學生'), et:ET.donut},
 {f:'ice-cream', en:'ice cream', zh:'冰淇淋', g:'i1', cat:'零食', ic:'🍦',
  tk:[['ice','冰','🧊'],['cream','奶油','🥛']], ex:'我喜歡冰淇淋。',
  ev:E('📊 小學生愛吃冰淇淋嗎？','jp',JP,[{tx:'零食排行有一整個「<b>アイス</b>」（冰淇淋）部門，排到第 1～5 名',ic:'🍦'}],S('J3'),'日本小學生最喜歡的零食，<b>冰淇淋自己就有一個部門</b>。'), et:ET.icecream},
 {f:'bubble-tea', en:'bubble tea', zh:'珍珠奶茶', g:'i1', cat:'飲料', ic:I.bubbletea,
  tk:[['bubble','泡泡',''],['tea','茶','🍵']], ex:'我喜歡珍珠奶茶。',
  ev:E('📊 台灣小朋友常喝珍奶嗎？','tw','台灣學童',[{p:16.2,l:'一個星期有 <b>3 天以上</b>喝手搖飲'},{tx:'記者會擺出「<b>全糖珍奶</b>」，提醒小朋友少喝',ic:I.bubbletea}],S('S3'),'<b>16.2%</b> 的學童一週有 3 天以上喝手搖飲；記者會還擺出<b>全糖珍奶</b>。',2,'學童'), et:ET.tea},
 {f:'cola', en:'cola', zh:'可樂', g:'i1', cat:'飲料', ic:'🥤',
  tk:[['cola','可樂','🥤']], ex:'我喜歡可樂。',
  ev:E('📊 小學生愛喝可樂嗎？','jp','日本一年級',[{p:21.4,l:'最喜歡的飲料：<b>コーラ</b>（可樂）'},{rk:7,l:'可樂是<b>第 7 名</b>（男生第 5 名）'}],S('HK'),'日本一年級：<b>21.4%</b> 最喜歡<b>可樂</b>，第 7 名。（一年級，爸媽陪著選）',2,'一年級'), et:ET.cola},
 {f:'juice', en:'juice', zh:'果汁', g:'i1', cat:'飲料', ic:'🧃',
  tk:[['juice','果汁','🧃']], ex:'我喜歡果汁。',
  ev:E('📊 小學生愛喝果汁嗎？','jp','日本一年級',[{p:39,l:'第 1 名：<b>蘋果汁</b>',txt:'39.0%'},{p:29.2,l:'第 3 名：<b>柳橙汁</b>'},{p:25.4,l:'第 4 名：<b>葡萄汁</b>'}],S('HK'),'<b>蘋果汁 39.0% 第 1 名</b>；前 4 名有 3 個是果汁。',4,'一年級'), et:ET.juice},
 {f:'french-fries', en:'French fries', zh:'薯條', g:'i1', cat:'美食', ic:'🍟',
  tk:[['French','法國的',WF('fr')],['fries','炸的東西','🍟']], ex:'我喜歡薯條。',
  ev:E('📊 小學生愛吃薯條嗎？','jp',JP,[{p:25.5,l:'最喜歡的食物：<b>ポテトフライ</b>（薯條）'},{rk:3,l:'薯條是<b>第 3 名</b>'}],S('J1'),'日本小學生：<b>25.5%</b> 最喜歡<b>薯條</b>，第 3 名。',3,'小學生'), et:ET.fry},
 {f:'fried-chicken', en:'fried chicken', zh:'炸雞', g:'i1', cat:'美食', ic:'🍗',
  tk:[['fried','炸的','🍳'],['chicken','雞','🐔']], ex:'我喜歡炸雞。',
  ev:E('📊 小學生愛吃炸雞嗎？','jp',JP,[{p:23.8,l:'最喜歡的食物：<b>炸雞、唐揚雞</b>'},{rk:4,l:'炸雞是<b>第 4 名</b>'}],S('J1'),'日本小學生：<b>23.8%</b> 最喜歡<b>炸雞</b>，第 4 名。',2,'小學生'), et:ET.chicken},
 {f:'hamburgers', en:'hamburgers', zh:'漢堡', g:'i1', cat:'美食', ic:'🍔',
  tk:[['hamburgers','漢堡','🍔']], ex:'我喜歡漢堡。',
  ev:E('📊 小學生愛吃漢堡嗎？','kr',KR,[{p:26,l:'便利商店最想吃：<b>漢堡</b>'},{rk:2,l:'漢堡是<b>第 2 名</b>'}],S('K1'),'韓國小學生：<b>26%</b> 最想吃<b>漢堡</b>，第 2 名。',3,'小學生'), et:ET.hamburger},
 {f:'hot-dogs', en:'hot dogs', zh:'熱狗', g:'i1', cat:'美食', ic:'🌭',
  tk:[['hot','熱的','🔥'],['dogs','狗','🐶']], ex:'我喜歡熱狗。',
  ev:E('📊 台灣小朋友常吃熱狗嗎？','tw','台灣學童',[{p:12.4,l:'<b>早餐</b>會吃<b>熱狗</b>、雞塊這些炸物'}],S('S3'),'<b>12.4%</b> 的學童早餐會吃<b>熱狗</b>、雞塊。（這是「吃什麼」，不是「最喜歡」）',1,'學童')},
 {f:'spaghetti', en:'spaghetti', zh:'義大利麵', g:'i1', cat:'美食', ic:'🍝',
  tk:[['spaghetti','義大利麵','🍝']], ex:'我喜歡義大利麵。',
  ev:E('📊 小學生愛吃義大利麵嗎？','jp',JP,[{p:9.8,l:'最喜歡的食物：<b>スパゲティ・パスタ</b>'},{rk:13,l:'義大利麵是<b>第 13 名</b>'}],S('G25'),'日本 1,200 名小學生：<b>9.8%</b> 最喜歡<b>義大利麵</b>，第 13 名。',1,'小學生'), et:ET.spaghetti},
 {f:'sushi', en:'sushi', zh:'壽司', g:'i1', cat:'美食', ic:'🍣',
  tk:[['sushi','壽司','🍣']], ex:'我喜歡壽司。',
  ev:E('📊 小學生愛吃壽司嗎？','jp',JP,[{p:39.9,l:'最喜歡的食物：<b>お寿司</b>（壽司）'},{rk:1,l:'壽司是<b>第 1 名</b>'}],S('J1','J3'),'日本小學生：<b>39.9%</b> 最喜歡<b>壽司</b>，兩份調查都是<b>第 1 名</b>。',4,'小學生'), et:ET.sushi},
 {f:'ramen', en:'ramen', zh:'拉麵', g:'i1', cat:'美食', ic:'🍜',
  tk:[['ramen','拉麵','🍜']], ex:'我喜歡拉麵。',
  ev:E('📊 小學生愛吃拉麵嗎？','jp',JP,[{p:28,l:'最喜歡的食物：<b>ラーメン</b>（拉麵）',txt:'28.0%'},{rk:2,l:'拉麵是<b>第 2 名</b>'}],S('J1'),'日本小學生：<b>28.0%</b> 最喜歡<b>拉麵</b>，第 2 名。',3,'小學生'), et:ET.ramen},
 {f:'curry', en:'curry', zh:'咖哩', g:'i1', cat:'美食', ic:'🍛',
  tk:[['curry','咖哩','🍛']], ex:'我喜歡咖哩。',
  ev:E('📊 小學生愛吃咖哩嗎？','tw','台灣學生',[{rk:3,l:'營養午餐最愛的菜：<b>咖哩類</b>'},{p:20.3,l:'日本小學生最喜歡：<b>カレーライス</b>（第 5 名）'}],S('S4','J1'),'台灣學生最愛的午餐菜色，<b>咖哩第 3 名</b>；日本小學生 <b>20.3%</b> 最喜歡咖哩飯。'), et:ET.curry},
 {f:'pizza', en:'pizza', zh:'披薩', g:'i1', cat:'美食', ic:'🍕',
  tk:[['pizza','披薩','🍕']], ex:'我喜歡披薩。',
  ev:E('📊 小學生愛吃披薩嗎？','jp',JP,[{p:15.8,l:'最喜歡的食物：<b>ピザ</b>（披薩）'},{rk:8,l:'披薩是<b>第 8 名</b>'}],S('G25'),'日本 1,200 名小學生：<b>15.8%</b> 最喜歡<b>披薩</b>，第 8 名。',2,'小學生'), et:ET.pizza},
 {f:'strawberries', en:'strawberries', zh:'草莓', g:'i1', cat:'水果', ic:'🍓',
  tk:[['strawberries','草莓','🍓']], pt:'🧩 {{straw}} 稻草 ＋ {{berry}} 莓果', ex:'我喜歡草莓。',
  ev:E('📊 小學生愛吃草莓嗎？','jp',JP,[{rk:2,l:'最喜歡的食物：<b>いちご</b>（草莓）'}],S('J3'),'日本小學生最喜歡的食物，<b>草莓第 2 名</b>（第 1 名是壽司）。'), et:ET.strawberry},
 {f:'milk', en:'milk', zh:'牛奶', g:'i1', cat:'飲料', ic:'🥛',
  tk:[['milk','牛奶','🥛']], ex:'我喜歡牛奶。',
  ev:E('📊 小學生愛喝牛奶嗎？','jp','日本一年級',[{p:30.8,l:'最喜歡的飲料：<b>牛乳</b>（牛奶）'},{rk:2,l:'牛奶是<b>第 2 名</b>'},{p:11,l:'韓國小學生最想買：<b>牛奶</b>（第 4 名）'}],S('HK','K1'),'日本一年級 <b>30.8%</b> 最喜歡牛奶（第 2 名）。',3,'一年級'), et:ET.milk},
 {f:'stuffed-animals', en:'stuffed animals', zh:'絨毛娃娃', g:'i1', cat:'玩具', ic:'🧸',
  tk:[['stuffed','塞滿的','🧵'],['animals','動物','🐻']], ex:'我喜歡絨毛娃娃。',
  ev:E('📊 小學生愛絨毛娃娃嗎？','jp','日本小學女生',[{rk:1,l:'女生的「<b>寶物</b>」：<b>ぬいぐるみ</b>（絨毛娃娃）'}],S('J4'),'日本小學女生的寶物，<b>絨毛娃娃第 1 名</b>。'), et:ET.stuffed},
 {f:'beyblades', en:'Beyblades', zh:'戰鬥陀螺', g:'i1', cat:'玩具', ic:I.beyblade,
  tk:[['Beyblades','戰鬥陀螺',I.beyblade]], ex:'我喜歡戰鬥陀螺。',
  ev:E('📊 小學生愛戰鬥陀螺嗎？','jp','日本小學男生',[{rk:1,l:'男生「<b>最想要的東西</b>」：<b>ベイブレード X</b>'},{rk:3,l:'男生和朋友最熱中的事：<b>戰鬥陀螺</b>這類玩具'}],S('J4'),'日本小學男生最想要的東西，<b>戰鬥陀螺第 1 名</b>。')},
 {f:'stickers', en:'stickers', zh:'貼紙', g:'i1', cat:'玩具', ic:I.stickers,
  tk:[['stickers','貼紙',I.stickers]], pt:'🧩 {{stick}} 黏住 ＋ <b class="nosay">er</b> ＝ <b>會黏住的東西</b>', ex:'我喜歡貼紙。',
  ev:E('📊 小學生真的愛貼紙嗎？','jp',JP,[{p:77.5,l:'正熱衷<b>收集貼紙</b>'},{p:90,l:'有貼紙本的：<b>會跟朋友交換</b>',txt:'9 成'}],S('NS'),'<b>77.5%</b> 的小學生<b>正熱衷收集貼紙</b>；有貼紙本的，<b>九成</b>會交換。',8,'小學生'), et:ET.sticker},
 {f:'dolls', en:'dolls', zh:'娃娃', g:'i1', cat:'玩具', ic:I.doll,
  tk:[['dolls','娃娃',I.doll]], ex:'我喜歡娃娃。',
  ev:E('📊 為什麼選 dolls？','jp','日本小學女生',[{tp:1,l:'<b>老師選的字</b>（2026-10-01）'},{rk:5,l:'女生的「<b>寶物</b>」：<b>人形</b>（娃娃）'},{tx:'聖誕禮物調查：<b>娃娃</b>是孩子想要的玩具之一（沒有百分比）',ic:'🎁'}],S('J4','BD'),'老師選的字。日本小學女生的寶物，<b>娃娃第 5 名</b>。'), et:ET.doll},
/* ══ 物品2（24）：3C、電玩／手遊、球類、書和漫畫、生活愛用品 ══ */
 {f:'smartphones', en:'smartphones', zh:'智慧型手機', g:'i2', cat:'3C', ic:'📱',
  tk:[['smartphones','智慧型手機','📱']], pt:'🧩 {{smart}} 聰明的 ＋ {{phone}} 電話', ex:'我喜歡智慧型手機。',
  ev:E('📊 小學生有手機嗎？','tw',TW,[{p:59.7,l:'國小生有<b>智慧型手機</b>'}],S('S7'),'教育部調查：<b>59.7%</b> 的國小生有<b>智慧型手機</b>。',6,'小學生'), et:ET.smartphone},
 {f:'tablets', en:'tablets', zh:'平板電腦', g:'i2', cat:'3C', ic:I.tablet,
  tk:[['tablets','平板電腦',I.tablet]], ex:'我喜歡平板電腦。',
  ev:E('📊 小學生有平板嗎？','tw',TW,[{p:46.5,l:'國小生有<b>平板電腦</b>（含筆電）'}],S('S7'),'教育部調查：<b>46.5%</b> 的國小生有<b>平板電腦</b>（含筆電）。',5,'小學生'), et:ET.tablet},
 {f:'youtube-videos', en:'YouTube videos', zh:'YouTube 影片', g:'i2', cat:'3C', ic:I.youtube,
  tk:[['YouTube','YouTube',I.youtube],['videos','影片','🎬']], ex:'我喜歡 YouTube 影片。',
  ev:E('📊 小學生愛看 YouTube 嗎？','jp',JP,[{tx:'年度調查有一整份「<b>最常看的 YouTube 頻道</b>」排行（男生、女生各一份）',ic:I.youtube}],S('J4'),'日本小學生年度調查，<b>男生、女生都有「最常看的 YouTube 頻道」排行</b>。'), et:ET.video},
 {f:'tv', en:'TV', zh:'電視', g:'i2', cat:'3C', ic:'📺',
  tk:[['TV','電視','📺']], pt:'🧩 TV ＝ {{television}} 的簡稱', ex:'我喜歡電視。',
  ev:E('📊 小學生愛看電視嗎？','jp',JP,[{tx:'放學後花最久的事：<b>看電視</b>，平均 <b>77 分鐘</b>',ic:'⏰'},{p:17.2,l:'最快樂的事：<b>テレビ</b>（電視）'},{rk:4,l:'電視是<b>第 4 名</b>'}],S('G25'),'日本小學生放學後<b>看電視最久（77 分鐘）</b>；<b>17.2%</b> 說最快樂的事是看電視。',2,'小學生'), et:ET.tv},
 {f:'video-games', en:'video games', zh:'電玩', g:'i2', cat:'電玩', ic:'🎮',
  tk:[['video','影像','📺'],['games','遊戲','🎮']], ex:'我喜歡電玩。',
  ev:E('📊 小學生愛玩電玩嗎？','tw',TW,[{p:79.7,l:'上網最常做：<b>玩手機遊戲</b>（含線上遊戲）'},{rk:1,l:'日本小學男生和朋友最熱中：<b>ゲーム</b>（遊戲）'}],S('S7','J4'),'台灣國小生上網，<b>79.7%</b> 最常<b>玩遊戲</b>；日本小學男生最熱中的也是<b>遊戲</b>。',8,'小學生'), et:ET.game},
 {f:'minecraft', en:'Minecraft', zh:'當個創世神', g:'i2', cat:'電玩', ic:I.minecraft,
  tk:[['Minecraft','當個創世神',I.minecraft]], ex:'我喜歡當個創世神。',
  ev:E('📊 小學生愛玩 Minecraft 嗎？','tw','App Store 台灣 2025',[{rk:1,l:'付費 App 排行：<b>Minecraft</b>'},{rk:2,l:'日本小學女生最常玩：<b>マインクラフト</b>'}],S('S8','J4'),'App Store 台灣 2025 <b>付費第 1 名</b>；日本小學女生最常玩<b>第 2 名</b>。')},
 {f:'roblox', en:'Roblox', zh:'機器磚塊', g:'i2', cat:'電玩', ic:I.roblox,
  tk:[['Roblox','機器磚塊',I.roblox]], ex:'我喜歡機器磚塊。',
  ev:E('📊 小學生愛玩 Roblox 嗎？','gb','英國 7～12 歲',[{rk:1,l:'玩手遊的<b>第 1 選擇</b>：<b>Roblox</b>'},{p:75,l:'美國 9～12 歲：<b>常玩 Roblox</b>',txt:'約 75%'},{rk:5,l:'日本小學女生最常玩：<b>ロブロックス</b>'}],S('U3','U5','J4'),'英國 7～12 歲玩手遊<b>第 1 選擇</b>；美國 9～12 歲大約 <b>75%</b> 常玩。',8,'小朋友')},
 {f:'pokemon-tcg-pocket', en:'Pokémon TCG Pocket', zh:'寶可夢卡牌手遊', g:'i2', cat:'手遊', ic:I.cardapp,
  tk:[['Pokémon TCG Pocket','寶可夢卡牌手遊',I.cardapp]], ex:'我喜歡寶可夢卡牌手遊。',
  ev:E('📊 小學生愛玩寶可夢卡牌手遊嗎？','tw','台灣 2025',[{tx:'App Store 台灣 2025 <b>免費排行上榜</b>',ic:'📱'},{tx:'Google Play 台灣 2025 <b>年度最佳休閒遊戲</b>',ic:'🏆'},{rk:3,l:'日本小學女生最常玩'}],S('S8','S9','J4'),'Google Play 台灣 2025 <b>年度最佳休閒遊戲</b>。'), et:ET.pokemon},
 {f:'splatoon', en:'Splatoon', zh:'漆彈大作戰', g:'i2', cat:'手遊', ic:I.splat,
  tk:[['Splatoon','漆彈大作戰',I.splat]], ex:'我喜歡漆彈大作戰。',
  ev:E('📊 小學生愛玩漆彈大作戰嗎？','jp','日本小學女生',[{rk:4,l:'女生最常玩的遊戲：<b>スプラトゥーン 3</b>'}],S('J4'),'日本小學女生最常玩的遊戲，<b>漆彈大作戰第 4 名</b>。')},
 {f:'mario-kart', en:'Mario Kart', zh:'瑪利歐賽車', g:'i2', cat:'電玩', ic:I.kart,
  tk:[['Mario Kart','瑪利歐賽車',I.kart]], ex:'我喜歡瑪利歐賽車。',
  ev:E('📊 小學生愛玩瑪利歐賽車嗎？','jp','日本小學男生',[{rk:2,l:'男生最想要的遊戲：<b>マリオカート ワールド</b>'},{tx:'賣了 <b>1,539 萬套</b>（到 2026-06-30），Switch 2 最暢銷',ic:'🌍'}],S('J4','WK'),'日本小學男生最想要的遊戲<b>第 2 名</b>；全世界賣了 <b>1,539 萬套</b>。'), et:ET.kart},
 {f:'animal-crossing', en:'Animal Crossing', zh:'動物森友會', g:'i2', cat:'電玩', ic:I.island,
  tk:[['Animal Crossing','動物森友會',I.island]], ex:'我喜歡動物森友會。',
  ev:E('📊 小學生愛玩動物森友會嗎？','jp','日本小學女生',[{rk:1,l:'女生最常玩的遊戲：<b>あつまれ どうぶつの森</b>'}],S('J4'),'日本小學女生最常玩的遊戲，<b>動物森友會第 1 名</b>。'), et:ET.animal},
 {f:'switch-games', en:'Switch games', zh:'Switch 遊戲', g:'i2', cat:'電玩', ic:I.console,
  tk:[['Switch','Switch',I.console],['games','遊戲','🎮']], ex:'我喜歡 Switch 遊戲。',
  ev:E('📊 小學生想要 Switch 嗎？','jp',JP,[{rk:2,l:'男生、女生「<b>最想要的東西</b>」：<b>Nintendo Switch</b>'},{tx:'⚠️ 想要的是 <b>Switch 遊戲機</b>（玩 Switch 遊戲要用的）',ic:I.console}],S('J4'),'日本小學男生、女生最想要的東西，<b>Switch 遊戲機都是第 2 名</b>。'), et:ET.game},
 {f:'basketball', en:'basketball', zh:'籃球', g:'i2', cat:'球類', ic:'🏀',
  tk:[['basketball','籃球','🏀']], pt:'🧩 {{basket}} 籃子 ＋ {{ball}} 球', ex:'我喜歡籃球。',
  ev:E('📊 台灣小朋友愛籃球嗎？','tw','台灣國中小男生',[{p:59.4,l:'<b>最喜歡籃球</b>'}],S('S10'),'<b>59.4%</b> 的男生<b>最喜歡籃球</b>。',6,'男生'), et:ET.basketball},
 {f:'badminton', en:'badminton', zh:'羽毛球', g:'i2', cat:'球類', ic:I.shuttle,
  tk:[['badminton','羽毛球',I.shuttle]], ex:'我喜歡羽毛球。',
  ev:E('📊 台灣小朋友愛羽毛球嗎？','tw','台灣國中小女生',[{p:68.6,l:'最喜歡<b>羽球</b>'}],S('S10'),'<b>68.6%</b> 的女生最喜歡<b>羽球</b>。',7,'女生'), et:ET.badminton},
 {f:'soccer', en:'soccer', zh:'足球', g:'i2', cat:'球類', ic:'⚽',
  tk:[['soccer','足球','⚽']], ex:'我喜歡足球。',
  ev:E('📊 小學生愛足球嗎？','jp',JP,[{rk:8,l:'才藝課排行：<b>足球</b>'},{rk:4,l:'男生和朋友最熱中：<b>サッカー</b>（足球）'}],S('J2','J4'),'日本小學生才藝課<b>足球第 8 名</b>；男生和朋友最熱中<b>第 4 名</b>。'), et:ET.soccer},
 {f:'baseball', en:'baseball', zh:'棒球', g:'i2', cat:'球類', ic:'⚾',
  tk:[['baseball','棒球','⚾']], pt:'🧩 {{base}} 壘 ＋ {{ball}} 球', ex:'我喜歡棒球。',
  ev:E('📊 小學生打棒球嗎？','jp',JP,[{rk:13,l:'才藝課排行：<b>棒球、壘球</b>'}],S('J2'),'日本小學生才藝課，<b>棒球第 13 名</b>。'), et:ET.baseball},
 {f:'comics', en:'comics', zh:'漫畫', g:'i2', cat:'漫畫', ic:I.comic,
  tk:[['comics','漫畫',I.comic]], ex:'我喜歡漫畫。',
  ev:E('📊 小學生愛看漫畫嗎？','tw','台灣高年級',[{rk:1,l:'最喜歡的課外書：<b>漫畫</b>'},{rk:1,l:'日本小學女生最想要：<b>書、漫畫</b>'}],S('S17','J4'),'台灣高年級最喜歡的課外書，<b>漫畫第 1 名</b>。'), et:ET.comic},
 {f:'picture-books', en:'picture books', zh:'繪本', g:'i2', cat:'書', ic:'📖',
  tk:[['picture','圖畫','🖼️'],['books','書','📚']], ex:'我喜歡繪本。',
  ev:E('📊 小學生愛看繪本嗎？','jp',JP,[{p:11.8,l:'最喜歡的書：<b>絵本</b>（繪本）'},{p:28.5,l:'<b>一年級</b>最喜歡繪本'},{rk:4,l:'繪本是<b>第 4 名</b>'}],S('G24'),'日本小學生 <b>11.8%</b> 最喜歡<b>繪本</b>（第 4 名），一年級高達 <b>28.5%</b>。',1,'小學生'), et:ET.picture},
 {f:'detective-stories', en:'detective stories', zh:'偵探故事', g:'i2', cat:'書', ic:'🕵️',
  tk:[['detective','偵探','🕵️'],['stories','故事','📖']], ex:'我喜歡偵探故事。',
  ev:E('📊 小學生愛看偵探故事嗎？','tw','台灣國小',[{tx:'<b>低年級</b>最喜歡的課外書：幽默、童話、<b>偵探冒險</b>',ic:'🔍'},{tx:'<b>中年級</b>最喜歡的課外書：幽默、<b>偵探冒險</b>、奇幻',ic:'🔍'}],S('S17'),'台灣低年級、中年級最喜歡的課外書，都有<b>偵探冒險</b>。'), et:ET.detective},
 {f:'science-comics', en:'science comics', zh:'科學漫畫', g:'i2', cat:'漫畫', ic:'🔬',
  tk:[['science','科學','🔬'],['comics','漫畫',I.comic]], ex:'我喜歡科學漫畫。',
  ev:E('📊 小學生愛看科學漫畫嗎？','tw','台灣國中小',[{tx:'近年很多孩子喜歡<b>學習漫畫</b>，像《達克比辦案》',ic:'🔬'}],S('S17'),'調查報導：近年<b>學習漫畫</b>（像《達克比辦案》）受到很多孩子喜愛。'), et:ET.science},
 {f:'books', en:'books', zh:'書', g:'i2', cat:'書', ic:'📚',
  tk:[['books','書','📚']], ex:'我喜歡書。',
  ev:E('📊 小學生愛書嗎？','jp','日本小學女生',[{rk:1,l:'女生「<b>最想要的東西</b>」：<b>本・まんが</b>（書、漫畫）'},{rk:2,l:'女生的興趣：<b>讀書・看漫畫</b>'}],S('J4','S17'),'日本小學女生最想要的東西，<b>書和漫畫第 1 名</b>。'), et:ET.book},
 {f:'music', en:'music', zh:'音樂', g:'i2', cat:'生活愛用品', ic:'🎵',
  tk:[['music','音樂','🎵']], ex:'我喜歡音樂。',
  ev:E('📊 小學生愛音樂嗎？','jp',JP,[{p:87,l:'用 YouTube 等影音平台<b>聽音樂</b>'},{p:12.7,l:'才藝課：<b>音樂教室</b>（唱歌、樂器）第 4 名'},{tx:'還有「小學生最喜歡的歌手」排行（第 1 名 Mrs. GREEN APPLE）',ic:'🎤'}],S('NM','G25','SG'),'<b>87%</b> 的日本小中學生用影音平台<b>聽音樂</b>。',9,'小朋友'), et:ET.music},
 {f:'dogs', en:'dogs', zh:'狗', g:'i2', cat:'生活愛用品', ic:'🐶',
  tk:[['dogs','狗','🐶']], ex:'我喜歡狗。',
  ev:E('📊 小朋友愛狗嗎？','jp',JP,[{rk:1,l:'家裡養的寵物：<b>イヌ</b>（狗）'},{rk:2,l:'最想養的寵物：<b>狗</b>'}],S('NF'),'日本小中學生家裡養的寵物，<b>狗第 1 名</b>。'), et:ET.dog},
 {f:'cats', en:'cats', zh:'貓', g:'i2', cat:'生活愛用品', ic:'🐱',
  tk:[['cats','貓','🐱']], ex:'我喜歡貓。',
  ev:E('📊 小朋友愛貓嗎？','jp',JP,[{rk:1,l:'最想養的寵物：<b>ネコ</b>（貓）'},{rk:2,l:'家裡養的寵物：<b>貓</b>'}],S('NF'),'日本小中學生最想養的寵物，<b>貓第 1 名</b>。'), et:ET.cat},
/* ══ 活動1（22）：球類運動、個人運動、才藝、戶外玩耍 ══ */
 {f:'play-basketball', en:'play basketball', zh:'打 籃球', g:'a1', cat:'球類運動', ic:'⛹️',
  tk:[['play','打','⛹️'],['basketball','籃球','🏀']], pt:'🧩 {{basket}} 籃子 ＋ {{ball}} 球', ex:'我喜歡打籃球。',
  ev:E('📊 台灣小朋友愛打籃球嗎？','tw','台灣國中小男生',[{p:59.4,l:'<b>最喜歡籃球</b>'}],S('S10'),'<b>59.4%</b> 的男生<b>最喜歡籃球</b>。',6,'男生'), et:ET.basketball},
 {f:'play-badminton', en:'play badminton', zh:'打 羽毛球', g:'a1', cat:'球類運動', ic:'🏸',
  tk:[['play','打','🏸'],['badminton','羽毛球',I.shuttle]], ex:'我喜歡打羽毛球。',
  ev:E('📊 台灣小朋友愛打羽毛球嗎？','tw','台灣國中小女生',[{p:68.6,l:'最喜歡<b>羽球</b>'}],S('S10'),'<b>68.6%</b> 的女生最喜歡<b>羽球</b>。',7,'女生'), et:ET.badminton},
 {f:'play-soccer', en:'play soccer', zh:'踢 足球', g:'a1', cat:'球類運動', ic:'⚽',
  tk:[['play','踢','🦵'],['soccer','足球','⚽']], ex:'我喜歡踢足球。',
  ev:E('📊 小學生愛踢足球嗎？','jp',JP,[{rk:8,l:'才藝課排行：<b>足球</b>'},{rk:4,l:'男生和朋友最熱中：<b>サッカー</b>（足球）'}],S('J2','J4'),'日本小學生才藝課<b>足球第 8 名</b>；男生和朋友最熱中<b>第 4 名</b>。'), et:ET.soccer},
 {f:'play-baseball', en:'play baseball', zh:'打 棒球', g:'a1', cat:'球類運動', ic:I.bat,
  tk:[['play','打',I.bat],['baseball','棒球','⚾']], pt:'🧩 {{base}} 壘 ＋ {{ball}} 球', ex:'我喜歡打棒球。',
  ev:E('📊 小學生打棒球嗎？','jp',JP,[{rk:13,l:'才藝課排行：<b>棒球、壘球</b>'}],S('J2'),'日本小學生才藝課，<b>棒球第 13 名</b>。'), et:ET.baseball},
 {f:'play-dodgeball', en:'play dodgeball', zh:'打 躲避球', g:'a1', cat:'球類運動', ic:'🤾',
  tk:[['play','打','🤾'],['dodgeball','躲避球',I.dball]], pt:'🧩 {{dodge}} 閃躲 ＋ {{ball}} 球', ex:'我喜歡打躲避球。',
  ev:E('📊 為什麼選 play dodgeball？','tw','台灣小學',[{tp:1,l:'<b>老師選的字</b>（2026-10-01）'},{tx:'躲避球是台灣小學<b>體育課的共同記憶</b>（2019 年的文章；2024 以後還沒有兒童調查）',ic:I.dball}],S('YH'),'老師選的字。躲避球是台灣小學體育課常上的運動。'), et:ET.dodgeball},
 {f:'run', en:'run', zh:'跑步', g:'a1', cat:'個人運動', ic:'🏃',
  tk:[['run','跑步','🏃']], ex:'我喜歡跑步。',
  ev:E('📊 小朋友愛跑步嗎？','us','美國 6～17 歲',[{p:20.3,l:'最常做的戶外活動：<b>跑步、慢跑</b>'},{rk:4,l:'跑步是<b>第 4 名</b>'}],S('OIA'),'美國 6～17 歲最常做的戶外活動，<b>跑步第 4 名（20.3%）</b>。',2,'小朋友'), et:ET.run},
 {f:'swim', en:'swim', zh:'游泳', g:'a1', cat:'個人運動', ic:'🏊',
  tk:[['swim','游泳','🏊']], ex:'我喜歡游泳。',
  ev:E('📊 小學生愛游泳嗎？','jp',JP,[{rk:1,l:'才藝課排行：<b>水泳</b>（游泳）'},{tx:'台灣家長最常討論的才藝：運動類的<b>游泳</b>',ic:'🏊'}],S('J2','S20'),'日本小學生的才藝課，<b>游泳第 1 名</b>。'), et:ET.swim},
 {f:'ride-my-bike', en:'ride my bike', zh:'騎 我的 腳踏車', g:'a1', cat:'個人運動', ic:'🚴',
  tk:[['ride','騎','🚴'],['my','我的','🙋'],['bike','腳踏車','🚲']], pt:'🧩 bike ＝ {{bicycle}} 的簡稱', ex:'我喜歡騎我的腳踏車。',
  ev:E('📊 小朋友愛騎腳踏車嗎？','us','美國 6～17 歲',[{p:27.8,l:'最常做的戶外活動：<b>騎腳踏車</b>'},{rk:2,l:'騎腳踏車是<b>第 2 名</b>'}],S('OIA'),'美國 6～17 歲最常做的戶外活動，<b>騎腳踏車第 2 名（27.8%）</b>。',3,'小朋友'), et:ET.bike},
 {f:'go-camping', en:'go camping', zh:'去 露營', g:'a1', cat:'個人運動', ic:'🏕️',
  tk:[['go','去','🚶'],['camping','露營','🏕️']], ex:'我喜歡去露營。',
  ev:E('📊 小朋友愛露營嗎？','us','美國 6～17 歲',[{p:29.1,l:'最常做的戶外活動：<b>露營</b>'},{rk:1,l:'露營是<b>第 1 名</b>'},{p:15.8,l:'日本小學生暑假想去：<b>露營、烤肉</b>'}],S('OIA','G24'),'美國 6～17 歲：<b>露營第 1 名</b>（29.1%）。',3,'小朋友'), et:ET.camp},
 {f:'play-the-piano', en:'play the piano', zh:'彈 鋼琴', g:'a1', cat:'才藝', ic:'🎹',
  tk:[['play','彈','🖐️'],['the','',''],['piano','鋼琴','🎹']], ex:'我喜歡彈鋼琴。',
  ev:E('📊 小學生學鋼琴嗎？','jp',JP,[{p:18.5,l:'正在學的樂器：<b>ピアノ</b>（鋼琴）'},{rk:2,l:'鋼琴是<b>第 2 名</b>（第 1 名是「沒有學」）'},{tx:'「<b>想開始學</b>」的樂器，前三名也有鋼琴',ic:'🎹'}],S('SG'),'日本小學生 <b>18.5%</b> 正在學<b>鋼琴</b>，是學最多的樂器。',2,'小學生'), et:ET.piano},
 {f:'play-the-drums', en:'play the drums', zh:'打 鼓', g:'a1', cat:'才藝', ic:'🥁',
  tk:[['play','打',I.sticks],['the','',''],['drums','鼓','🥁']], ex:'我喜歡打鼓。',
  ev:E('📊 小學生想學打鼓嗎？','jp',JP,[{tx:'「<b>想開始學</b>」的樂器前三名：<b>ドラム</b>（鼓）、吉他、鋼琴',ic:'🥁'}],S('SG'),'日本小學生<b>想開始學的樂器，鼓在前三名</b>。'), et:ET.drum},
 {f:'do-taekwondo', en:'do taekwondo', zh:'學 跆拳道', g:'a1', cat:'才藝', ic:'🥋',
  tk:[['do','學','💪'],['taekwondo','跆拳道','🥋']], pt:'🧩 <b class="nosay">tae</b> 踢 ＋ <b class="nosay">kwon</b> 拳頭 ＋ <b class="nosay">do</b> 道（韓文）', ex:'我喜歡學跆拳道。',
  ev:E('📊 台灣小朋友學跆拳道嗎？','tw','台灣家長',[{rk:1,l:'最常討論的才藝類別：<b>運動</b>（游泳、<b>跆拳道</b>）'}],S('S20'),'台灣家長網路上最常討論的才藝，第 1 類運動就有<b>跆拳道</b>。'), et:ET.taekwondo},
 {f:'dance', en:'dance', zh:'跳舞', g:'a1', cat:'才藝', ic:'💃',
  tk:[['dance','跳舞','💃']], ex:'我喜歡跳舞。',
  ev:E('📊 小學生愛跳舞嗎？','jp',JP,[{rk:5,l:'女生的興趣：<b>ダンス</b>（跳舞）'},{rk:11,l:'才藝課排行：<b>跳舞</b>'}],S('J4','J2'),'日本小學女生的興趣，<b>跳舞第 5 名</b>。'), et:ET.dance},
 {f:'sing', en:'sing', zh:'唱歌', g:'a1', cat:'才藝', ic:'🎤',
  tk:[['sing','唱歌','🎤']], ex:'我喜歡唱歌。',
  ev:E('📊 小朋友愛唱歌嗎？','tw','台灣家長',[{tx:'網友推薦的才藝：「<b>開口就行的唱歌</b>」',ic:'🎤'},{rk:4,l:'日本小學生才藝課：<b>音樂教室</b>（唱歌、樂器）'}],S('S20','J2'),'台灣家長推薦<b>唱歌</b>；日本小學生的才藝課，音樂教室（唱歌、樂器）<b>第 4 名</b>。'), et:ET.sing},
 {f:'draw', en:'draw', zh:'畫畫', g:'a1', cat:'才藝', ic:'🎨',
  tk:[['draw','畫畫','🎨']], ex:'我喜歡畫畫。',
  ev:E('📊 小學生愛畫畫嗎？','jp','日本小學女生',[{rk:1,l:'女生的興趣：<b>絵を描く</b>（畫畫）'},{tx:'台灣家長常討論的才藝：美術類的<b>繪畫</b>',ic:'🎨'}],S('J4','S20'),'日本小學女生的興趣，<b>畫畫第 1 名</b>。'), et:ET.draw},
 {f:'speak-english', en:'speak English', zh:'說 英文', g:'a1', cat:'才藝', ic:'🗣️',
  tk:[['speak','說','🗣️'],['English','英文','🔤']], ex:'我喜歡說英文。',
  ev:E('📊 小學生學英文嗎？','jp',JP,[{rk:3,l:'才藝課排行：<b>英会話</b>（英語會話）'},{tx:'台灣家長常討論：讓孩子「<b>練好英文</b>」',ic:'🔤'}],S('J2','S20'),'日本小學生的才藝課，<b>英語會話第 3 名</b>。'), et:ET.english},
 {f:'do-crafts', en:'do crafts', zh:'做 手工藝', g:'a1', cat:'才藝', ic:'✂️',
  tk:[['do','做','💪'],['crafts','手工藝','✂️']], ex:'我喜歡做手工藝。',
  ev:E('📊 小學生學手工藝嗎？','jp',JP,[{rk:20,l:'才藝課排行：<b>手芸・料理</b>（手工藝、做菜）'}],S('J2'),'日本小學生的才藝課，<b>手工藝、做菜第 20 名</b>。'), et:ET.craft},
 {f:'play-in-the-park', en:'play in the park', zh:'在公園 玩', g:'a1', cat:'戶外玩耍', ic:'🏞️',
  tk:[['play','玩','🤸'],['in','在……裡',''],['the','',''],['park','公園','🏞️']], ex:'我喜歡在公園玩。',
  ev:E('📊 小學生愛在公園玩嗎？','jp',JP,[{p:27.7,l:'放學後最常玩的地方：<b>公園・運動場</b>'},{rk:2,l:'公園是<b>第 2 名</b>（第 1 名是家裡）'}],S('G25'),'日本小學生放學後最常玩的地方，<b>公園第 2 名（27.7%）</b>。',3,'小學生'), et:ET.park},
 {f:'play-outside', en:'play outside', zh:'在外面 玩', g:'a1', cat:'戶外玩耍', ic:'🌳',
  tk:[['play','玩','🤸'],['outside','在外面','🌳']], pt:'🧩 {{out}} 外 ＋ {{side}} 邊', ex:'我喜歡在外面玩。',
  ev:E('📊 小朋友愛在外面玩嗎？','us','美國 8～12 歲',[{p:45,l:'最喜歡<b>自由玩耍</b>（投籃、在社區探險）'},{rk:2,l:'日本小學男生最熱中：<b>在外面玩</b>'}],S('U5','J4'),'美國 8～12 歲：<b>45%</b> 最喜歡自由玩耍。',5,'小朋友'), et:ET.outside},
 {f:'play-tag', en:'play tag', zh:'玩 鬼抓人', g:'a1', cat:'戶外玩耍', ic:'🏃',
  tk:[['play','玩','🏃'],['tag','鬼抓人','👉']], ex:'我喜歡玩鬼抓人。',
  ev:E('📊 小學生愛玩鬼抓人嗎？','jp','日本小學男生',[{rk:2,l:'男生和朋友最熱中：<b>鬼ごっこ</b>（鬼抓人）這類外面玩的遊戲'}],S('J4'),'日本小學男生和朋友最熱中的事，<b>鬼抓人第 2 名</b>。'), et:ET.tag},
 {f:'play-the-guitar', en:'play the guitar', zh:'彈 吉他', g:'a1', cat:'才藝', ic:'🎸',
  tk:[['play','彈','🖐️'],['the','',''],['guitar','吉他','🎸']], ex:'我喜歡彈吉他。',
  ev:E('📊 小學生想學吉他嗎？','jp',JP,[{tx:'「<b>想開始學</b>」的樂器前三名：鼓、<b>ギター</b>（吉他）、鋼琴',ic:'🎸'},{p:2.5,l:'正在學的樂器：<b>吉他</b>（第 4 名）'}],S('SG'),'日本小學生<b>想開始學的樂器，吉他在前三名</b>。'), et:ET.guitar},
 {f:'do-magic-tricks', en:'do magic tricks', zh:'變 魔術', g:'a1', cat:'才藝', ic:'🎩',
  tk:[['do','變','💪'],['magic','魔術的','🎩'],['tricks','把戲','🃏']], ex:'我喜歡變魔術。',
  ev:E('📊 小學生學魔術嗎？','jp',JP,[{rk:21,l:'才藝課排行：<b>將棋、圍棋</b>（包含桌遊、<b>手品</b>魔術）'}],S('J2'),'日本小學生的才藝課，<b>包含魔術的那一類第 21 名</b>（跟將棋、圍棋放在一起）。'), et:ET.magic},
/* ══ 活動2（26）：3C 和電玩、競賽、靜態活動、家裡的活動、假日出遊 ══ */
 {f:'play-video-games', en:'play video games', zh:'打 電動', g:'a2', cat:'3C 和電玩', ic:'🕹️',
  tk:[['play','打','🕹️'],['video','影像','📺'],['games','遊戲','🎮']], ex:'我喜歡打電動。',
  ev:E('📊 小學生愛打電動嗎？','tw',TW,[{p:79.7,l:'上網最常做：<b>玩手機遊戲</b>（含線上遊戲）'}],S('S7'),'台灣國小生上網，<b>79.7%</b> 最常<b>玩遊戲</b>。',8,'小學生'), et:ET.video},
 {f:'play-mobile-games', en:'play mobile games', zh:'玩 手遊', g:'a2', cat:'3C 和電玩', ic:'📱',
  tk:[['play','玩','🎮'],['mobile','手機的','📱'],['games','遊戲','🎮']], ex:'我喜歡玩手遊。',
  ev:E('📊 小學生愛玩手遊嗎？','tw',TW,[{p:79.7,l:'上網最常做：<b>玩智慧型手機遊戲</b>'}],S('S7'),'台灣國小生上網，<b>79.7%</b> 最常<b>玩手機遊戲</b>。',8,'小學生'), et:ET.mobile},
 {f:'watch-videos', en:'watch videos', zh:'看 影片', g:'a2', cat:'3C 和電玩', ic:'🎬',
  tk:[['watch','看','👀'],['videos','影片','🎬']], ex:'我喜歡看影片。',
  ev:E('📊 小學生常看影片嗎？','tw',TW,[{p:61.1,l:'每週至少一次上網<b>找資料或看影片</b>（學習用）'},{tx:'日本小學生年度調查：「<b>最常看的 YouTube 頻道</b>」排行',ic:I.youtube}],S('S7','J4'),'台灣國小生 <b>61.1%</b> 每週上網找資料或<b>看影片</b>（學習用）。',6,'小學生'), et:ET.video},
 {f:'watch-tv', en:'watch TV', zh:'看 電視', g:'a2', cat:'3C 和電玩', ic:'📺',
  tk:[['watch','看','👀'],['TV','電視','📺']], pt:'🧩 TV ＝ {{television}} 的簡稱', ex:'我喜歡看電視。',
  ev:E('📊 小學生愛看電視嗎？','jp',JP,[{tx:'放學後花最久的事：<b>看電視</b>，平均 <b>77 分鐘</b>',ic:'⏰'},{p:17.2,l:'最快樂的事：<b>看電視</b>（第 4 名）'}],S('G25'),'日本小學生放學後<b>看電視最久（77 分鐘）</b>。',2,'小學生'), et:ET.tv},
 {f:'play-minecraft', en:'play Minecraft', zh:'玩 當個創世神', g:'a2', cat:'3C 和電玩', ic:I.minecraft,
  tk:[['play','玩','🎮'],['Minecraft','當個創世神',I.minecraft]], ex:'我喜歡玩當個創世神。',
  ev:E('📊 小學生愛玩 Minecraft 嗎？','tw','App Store 台灣 2025',[{rk:1,l:'付費 App 排行：<b>Minecraft</b>'},{rk:2,l:'日本小學女生最常玩：<b>マインクラフト</b>'}],S('S8','J4'),'App Store 台灣 2025 <b>付費第 1 名</b>；日本小學女生最常玩<b>第 2 名</b>。'), et:ET.game},
 {f:'play-roblox', en:'play Roblox', zh:'玩 機器磚塊', g:'a2', cat:'3C 和電玩', ic:I.roblox,
  tk:[['play','玩','🎮'],['Roblox','機器磚塊',I.roblox]], ex:'我喜歡玩機器磚塊。',
  ev:E('📊 小學生愛玩 Roblox 嗎？','gb','英國 7～12 歲',[{rk:1,l:'玩手遊的<b>第 1 選擇</b>：<b>Roblox</b>'},{p:75,l:'美國 9～12 歲：<b>常玩 Roblox</b>',txt:'約 75%'}],S('U3','U5'),'英國 7～12 歲玩手遊<b>第 1 選擇</b>；美國 9～12 歲大約 <b>75%</b> 常玩。',8,'小朋友'), et:ET.game},
 {f:'play-mario-kart', en:'play Mario Kart', zh:'玩 瑪利歐賽車', g:'a2', cat:'3C 和電玩', ic:I.kart,
  tk:[['play','玩','🎮'],['Mario Kart','瑪利歐賽車',I.kart]], ex:'我喜歡玩瑪利歐賽車。',
  ev:E('📊 小學生愛玩瑪利歐賽車嗎？','jp','日本小學男生',[{rk:2,l:'男生最想要的遊戲：<b>マリオカート ワールド</b>'},{tx:'賣了 <b>1,539 萬套</b>（到 2026-06-30），Switch 2 最暢銷',ic:'🌍'}],S('J4','WK'),'日本小學男生最想要的遊戲<b>第 2 名</b>；全世界賣了 <b>1,539 萬套</b>。'), et:ET.kart},
 {f:'collect-pokemon-cards', en:'collect Pokémon cards', zh:'收集 寶可夢卡', g:'a2', cat:'競賽', ic:I.card,
  tk:[['collect','收集','📦'],['Pokémon','寶可夢',I.card],['cards','卡','🃏']], ex:'我喜歡收集寶可夢卡。',
  ev:E('📊 小學生愛收集寶可夢卡嗎？','jp','日本小學男生',[{rk:4,l:'男生「<b>最想要的東西</b>」：<b>ポケモンカード</b>（寶可夢卡）'}],S('J4'),'日本小學男生最想要的東西，<b>寶可夢卡第 4 名</b>。'), et:ET.pokemon},
 {f:'play-beyblade', en:'play Beyblade', zh:'玩 戰鬥陀螺', g:'a2', cat:'競賽', ic:I.beyblade,
  tk:[['play','玩','🎮'],['Beyblade','戰鬥陀螺',I.beyblade]], ex:'我喜歡玩戰鬥陀螺。',
  ev:E('📊 小學生愛玩戰鬥陀螺嗎？','jp','日本小學男生',[{rk:3,l:'男生和朋友最熱中：<b>戰鬥陀螺</b>這類玩具'},{rk:1,l:'男生「<b>最想要的東西</b>」：<b>ベイブレード X</b>'}],S('J4'),'日本小學男生和朋友最熱中<b>第 3 名</b>；最想要的東西<b>第 1 名</b>。')},
 {f:'listen-to-music', en:'listen to music', zh:'聽 音樂', g:'a2', cat:'靜態活動', ic:'🎧',
  tk:[['listen','聽','👂'],['to','',''],['music','音樂','🎵']], ex:'我喜歡聽音樂。',
  ev:E('📊 小學生愛聽音樂嗎？','jp',JP,[{p:87,l:'用 YouTube 等影音平台<b>聽音樂</b>'},{p:50,l:'用<b>音樂 App</b> 聽音樂'}],S('NM'),'<b>87%</b> 的日本小中學生用影音平台<b>聽音樂</b>。',9,'小朋友'), et:ET.listen},
 {f:'read', en:'read', zh:'閱讀', g:'a2', cat:'靜態活動', ic:'📖',
  tk:[['read','閱讀','📖']], ex:'我喜歡閱讀。',
  ev:E('📊 小學生愛閱讀嗎？','jp','日本小學女生',[{rk:2,l:'女生的興趣：<b>読書・まんが</b>（讀書、看漫畫）'}],S('J4','S17'),'日本小學女生的興趣，<b>讀書、看漫畫第 2 名</b>。'), et:ET.read},
 {f:'read-comics', en:'read comics', zh:'看 漫畫', g:'a2', cat:'靜態活動', ic:I.comic,
  tk:[['read','看','📖'],['comics','漫畫',I.comic]], ex:'我喜歡看漫畫。',
  ev:E('📊 小學生愛看漫畫嗎？','tw','台灣高年級',[{rk:1,l:'最喜歡的課外書：<b>漫畫</b>'},{rk:2,l:'日本小學女生的興趣：<b>讀書・看漫畫</b>'}],S('S17','J4'),'台灣高年級最喜歡的課外書，<b>漫畫第 1 名</b>。'), et:ET.comic},
 {f:'chat-with-my-friends', en:'chat with my friends', zh:'跟朋友 聊天', g:'a2', cat:'靜態活動', ic:'💬',
  tk:[['chat','聊天','💬'],['with','和',''],['my','我的','🙋'],['friends','朋友','👫']], ex:'我喜歡跟朋友聊天。',
  ev:E('📊 小學生愛跟朋友聊天嗎？','jp',JP,[{p:26.1,l:'最快樂的事：<b>友だちとおしゃべり</b>（跟朋友聊天）'},{rk:2,l:'聊天是<b>第 2 名</b>'},{p:34.5,l:'女生：<b>第 1 名</b>'}],S('G25'),'日本小學生最快樂的事，<b>跟朋友聊天第 2 名（26.1%）</b>；女生是第 1 名。',3,'小學生'), et:ET.chat},
 {f:'eat-snacks', en:'eat snacks', zh:'吃 點心', g:'a2', cat:'靜態活動', ic:'🍪',
  tk:[['eat','吃','😋'],['snacks','點心','🍪']], ex:'我喜歡吃點心。',
  ev:E('📊 小學生愛吃點心嗎？','jp',JP,[{p:16.1,l:'最快樂的事：<b>おやつ</b>（吃點心）'},{rk:5,l:'吃點心是<b>第 5 名</b>（女生第 3 名）'}],S('G25'),'日本小學生最快樂的事，<b>吃點心第 5 名（16.1%）</b>。',2,'小學生'), et:ET.snack},
 {f:'play-with-toys', en:'play with toys', zh:'玩 玩具', g:'a2', cat:'家裡的活動', ic:'🧸',
  tk:[['play','玩','🤲'],['with','和',''],['toys','玩具','🧸']], ex:'我喜歡玩玩具。',
  ev:E('📊 小學生愛玩具嗎？','jp',JP,[{p:26.4,l:'壓歲錢拿來買：<b>おもちゃ</b>（玩具）'},{rk:2,l:'玩具是<b>第 2 名</b>'},{p:28.7,l:'零用錢拿來買：<b>玩具</b>（2024，第 2 名）'}],S('G25','G24'),'壓歲錢<b>買玩具第 2 名</b>（26.4%）。',3,'小學生'), et:ET.toy},
 {f:'cook', en:'cook', zh:'做菜', g:'a2', cat:'家裡的活動', ic:'🍳',
  tk:[['cook','做菜','🍳']], ex:'我喜歡做菜。',
  ev:E('📊 小學生學做菜嗎？','jp',JP,[{rk:20,l:'才藝課排行：<b>手芸・料理</b>（手工藝、做菜）'}],S('J2'),'日本小學生的才藝課，<b>做菜、手工藝第 20 名</b>（是才藝課）。'), et:ET.cook},
 {f:'stay-home', en:'stay home', zh:'待 在家', g:'a2', cat:'家裡的活動', ic:'🏠',
  tk:[['stay','待','🛋️'],['home','在家','🏠']], ex:'我喜歡待在家。',
  ev:E('📊 小學生常待在家嗎？','jp',JP,[{p:74.9,l:'放學後最常待的地方：<b>自宅</b>（家裡）'},{rk:1,l:'家裡是<b>第 1 名</b>'}],S('G25'),'日本小學生放學後最常待的地方，<b>家裡第 1 名（74.9%）</b>。',7,'小學生'), et:ET.home},
 {f:'make-videos', en:'make videos', zh:'拍 影片', g:'a2', cat:'家裡的活動', ic:'🎥',
  tk:[['make','拍','🎥'],['videos','影片','🎬']], ex:'我喜歡拍影片。',
  ev:E('📊 小學生學拍影片嗎？','jp',JP,[{rk:21,l:'才藝課排行：<b>動画制作・編集</b>（拍影片、剪影片）'}],S('J2'),'日本小學生的才藝課，<b>拍影片、剪影片第 21 名</b>（是才藝課）。'), et:ET.video},
 {f:'go-to-an-amusement-park', en:'go to an amusement park', zh:'去 遊樂園', g:'a2', cat:'假日出遊', ic:'🎡',
  tk:[['go','去','🚶'],['to','',''],['an','',''],['amusement','遊樂','🎢'],['park','園','🎡']], ex:'我喜歡去遊樂園。',
  ev:E('📊 小學生愛去遊樂園嗎？','jp',JP,[{p:58.2,l:'寒假想去：<b>テーマパーク・遊園地</b>'},{p:60.1,l:'春假想去：<b>遊樂園</b>'},{p:53.7,l:'暑假想去：<b>遊樂園</b>'}],S('G24'),'日本小學生寒假、春假、暑假想去的地方，<b>遊樂園都是第 1 名</b>。',6,'小學生'), et:ET.amusement},
 {f:'visit-my-grandparents', en:'visit my grandparents', zh:'去看 爺爺奶奶', g:'a2', cat:'假日出遊', ic:'👴',
  tk:[['visit','去看','🚗'],['my','我的','🙋'],['grandparents','爺爺奶奶','👵']], ex:'我喜歡去看爺爺奶奶。',
  ev:E('📊 小學生常去看爺爺奶奶嗎？','jp','日本小學生（雙薪家庭）',[{p:48.2,l:'長假在<b>爺爺奶奶</b>或親戚家過'},{tx:'比平常放學後多 <b>10.7</b> 個百分點（這是「去了多少」，不是「最喜歡」）',ic:'📈'}],S('NPO'),'長假時 <b>48.2%</b> 的小學生在<b>爺爺奶奶</b>或親戚家過。',5,'小學生'), et:ET.grandparents},
 {f:'go-shopping', en:'go shopping', zh:'去 買東西', g:'a2', cat:'假日出遊', ic:'🛍️',
  tk:[['go','去','🚶'],['shopping','買東西','🛍️']], ex:'我喜歡去買東西。',
  ev:E('📊 小朋友常去買東西嗎？','jp','日本小學生家長',[{tx:'假日親子一起<b>逛街買東西</b>：平均 <b>1 小時 1 分</b>',ic:'⏰'},{p:5,l:'小學生最快樂的事：<b>買い物</b>（買東西）',txt:'5.0%'}],S('CZ','G25'),'日本小學生假日跟爸媽<b>逛街買東西平均 1 小時 1 分</b>。'), et:ET.shopping},
 {f:'bake-cakes', en:'bake cakes', zh:'烤 蛋糕', g:'a2', cat:'家裡的活動', ic:'🎂',
  tk:[['bake','烤','🔥'],['cakes','蛋糕','🎂']], ex:'我喜歡烤蛋糕。',
  ev:E('📊 小學生愛做蛋糕嗎？','jp','日本小學女生',[{rk:1,l:'將來想做的職業：<b>パティシエ</b>（甜點師）'},{tx:'最多人的理由：「<b>喜歡做甜點、蛋糕</b>」',ic:'🎂'}],S('PT','J4'),'日本小學女生將來想做的職業，<b>甜點師第 1 名</b>，因為<b>喜歡做蛋糕</b>。'), et:ET.cake},
 {f:'play-with-my-dog', en:'play with my dog', zh:'和我的狗 玩', g:'a2', cat:'家裡的活動', ic:'🐕',
  tk:[['play','玩','🎾'],['with','和',''],['my','我的','🙋'],['dog','狗','🐶']], ex:'我喜歡和我的狗玩。',
  ev:E('📊 小朋友愛跟狗玩嗎？','jp',JP,[{rk:1,l:'家裡養的寵物：<b>狗</b>'},{tx:'養寵物的好處，孩子寫：「<b>可以一起玩</b>」',ic:'🎾'}],S('NF'),'日本小中學生家裡養的寵物<b>狗第 1 名</b>；好處是<b>可以一起玩</b>。'), et:ET.dog},
 {f:'collect-stickers', en:'collect stickers', zh:'收集 貼紙', g:'a2', cat:'家裡的活動', ic:I.stickers,
  tk:[['collect','收集','📦'],['stickers','貼紙',I.stickers]], ex:'我喜歡收集貼紙。',
  ev:E('📊 小學生真的愛收集貼紙嗎？','jp',JP,[{p:77.5,l:'正熱衷<b>收集貼紙</b>'},{p:90,l:'有貼紙本的：<b>會跟朋友交換</b>',txt:'9 成'}],S('NS'),'<b>77.5%</b> 的小學生<b>正熱衷收集貼紙</b>；有貼紙本的，<b>九成</b>會交換。',8,'小學生'), et:ET.collect},
 {f:'write-code', en:'write code', zh:'寫 程式', g:'a2', cat:'3C 和電玩', ic:'💻',
  tk:[['write','寫','✍️'],['code','程式','💻']], ex:'我喜歡寫程式。',
  ev:E('📊 小學生學寫程式嗎？','jp',JP,[{rk:16,l:'才藝課排行：<b>プログラミング</b>（寫程式）、機器人教室'}],S('J2'),'日本小學生的才藝課，<b>寫程式第 16 名</b>。'), et:ET.code},
 {f:'play-with-lego', en:'play with LEGO', zh:'玩 樂高', g:'a2', cat:'家裡的活動', ic:I.lego,
  tk:[['play','玩','🤲'],['with','和',''],['LEGO','樂高',I.lego]], ex:'我喜歡玩樂高。',
  ev:E('📊 為什麼選 play with LEGO？','','英文書裡怎麼說',[{tp:1,l:'<b>老師選的字</b>（2026-10-01）'},{tx:'英文書裡「<b>play with</b> Lego」比「build Lego」常用（每十億字 <b>9.86</b> 比 <b>7.90</b>）',ic:'📚'},{tx:'LEGO 官方：LEGO <b>不加 s</b>（不寫 Legos）',ic:I.lego}],S('NG'),'老師選的字。英文書裡最常說 <b>play with LEGO</b>；LEGO 官方規定不加 s。'), et:ET.lego}
];

module.exports = { RAW, PLAIN, WORDS };
